import numpy as np 
import pandas as pd 
from scipy import sparse 


jac_df=pd.DataFrame([15 *[None]],columns=['rbl_lca', 'rbl_strut_lower', 'rbl_strut_upper', 'rbl_tie_rod', 'rbl_uca', 'rbl_upright', 'rbl_wheel_hub', 'rbr_lca', 'rbr_strut_lower', 'rbr_strut_upper', 'rbr_tie_rod', 'rbr_uca', 'rbr_upright', 'rbr_wheel_hub', 'rbs_chassis'],index=['jcl_hub_bearing', 'jcl_lca_ch', 'jcl_lca_upright', 'jcl_strut_chassis_uni', 'jcl_strut_cyl', 'jcl_strut_lca_uni', 'jcl_tie_chassis', 'jcl_tie_upright', 'jcl_uca_ch', 'jcl_uca_upright', 'jcr_hub_bearing', 'jcr_lca_ch', 'jcr_lca_upright', 'jcr_strut_chassis_uni', 'jcr_strut_cyl', 'jcr_strut_lca_uni', 'jcr_tie_chassis', 'jcr_tie_upright', 'jcr_uca_ch', 'jcr_uca_upright', 'rbl_lca', 'rbl_strut_lower', 'rbl_strut_upper', 'rbl_tie_rod', 'rbl_uca', 'rbl_upright', 'rbl_wheel_hub', 'rbr_lca', 'rbr_strut_lower', 'rbr_strut_upper', 'rbr_tie_rod', 'rbr_uca', 'rbr_upright', 'rbr_wheel_hub', 'rbs_chassis', 'mcl_rotational_lock', 'mcr_rotational_lock', 'mcl_vertical', 'mcr_vertical'])
def cq(q,bodies,joints,actuators): 
	 jac_df.loc['jcl_hub_bearing','rbl_upright']=joints['jcl_hub_bearing'].jacobian_i(q)
	 jac_df.loc['jcl_hub_bearing','rbl_wheel_hub']=joints['jcl_hub_bearing'].jacobian_j(q)
	 jac_df.loc['jcl_lca_ch','rbl_lca']=joints['jcl_lca_ch'].jacobian_i(q)
	 jac_df.loc['jcl_lca_ch','rbs_chassis']=joints['jcl_lca_ch'].jacobian_j(q)
	 jac_df.loc['jcl_lca_upright','rbl_lca']=joints['jcl_lca_upright'].jacobian_i(q)
	 jac_df.loc['jcl_lca_upright','rbl_upright']=joints['jcl_lca_upright'].jacobian_j(q)
	 jac_df.loc['jcl_strut_chassis_uni','rbl_strut_upper']=joints['jcl_strut_chassis_uni'].jacobian_i(q)
	 jac_df.loc['jcl_strut_chassis_uni','rbs_chassis']=joints['jcl_strut_chassis_uni'].jacobian_j(q)
	 jac_df.loc['jcl_strut_cyl','rbl_strut_upper']=joints['jcl_strut_cyl'].jacobian_i(q)
	 jac_df.loc['jcl_strut_cyl','rbl_strut_lower']=joints['jcl_strut_cyl'].jacobian_j(q)
	 jac_df.loc['jcl_strut_lca_uni','rbl_strut_lower']=joints['jcl_strut_lca_uni'].jacobian_i(q)
	 jac_df.loc['jcl_strut_lca_uni','rbl_lca']=joints['jcl_strut_lca_uni'].jacobian_j(q)
	 jac_df.loc['jcl_tie_chassis','rbl_tie_rod']=joints['jcl_tie_chassis'].jacobian_i(q)
	 jac_df.loc['jcl_tie_chassis','rbs_chassis']=joints['jcl_tie_chassis'].jacobian_j(q)
	 jac_df.loc['jcl_tie_upright','rbl_tie_rod']=joints['jcl_tie_upright'].jacobian_i(q)
	 jac_df.loc['jcl_tie_upright','rbl_upright']=joints['jcl_tie_upright'].jacobian_j(q)
	 jac_df.loc['jcl_uca_ch','rbl_uca']=joints['jcl_uca_ch'].jacobian_i(q)
	 jac_df.loc['jcl_uca_ch','rbs_chassis']=joints['jcl_uca_ch'].jacobian_j(q)
	 jac_df.loc['jcl_uca_upright','rbl_uca']=joints['jcl_uca_upright'].jacobian_i(q)
	 jac_df.loc['jcl_uca_upright','rbl_upright']=joints['jcl_uca_upright'].jacobian_j(q)
	 jac_df.loc['jcr_hub_bearing','rbr_upright']=joints['jcr_hub_bearing'].jacobian_i(q)
	 jac_df.loc['jcr_hub_bearing','rbr_wheel_hub']=joints['jcr_hub_bearing'].jacobian_j(q)
	 jac_df.loc['jcr_lca_ch','rbr_lca']=joints['jcr_lca_ch'].jacobian_i(q)
	 jac_df.loc['jcr_lca_ch','rbs_chassis']=joints['jcr_lca_ch'].jacobian_j(q)
	 jac_df.loc['jcr_lca_upright','rbr_lca']=joints['jcr_lca_upright'].jacobian_i(q)
	 jac_df.loc['jcr_lca_upright','rbr_upright']=joints['jcr_lca_upright'].jacobian_j(q)
	 jac_df.loc['jcr_strut_chassis_uni','rbr_strut_upper']=joints['jcr_strut_chassis_uni'].jacobian_i(q)
	 jac_df.loc['jcr_strut_chassis_uni','rbs_chassis']=joints['jcr_strut_chassis_uni'].jacobian_j(q)
	 jac_df.loc['jcr_strut_cyl','rbr_strut_upper']=joints['jcr_strut_cyl'].jacobian_i(q)
	 jac_df.loc['jcr_strut_cyl','rbr_strut_lower']=joints['jcr_strut_cyl'].jacobian_j(q)
	 jac_df.loc['jcr_strut_lca_uni','rbr_strut_lower']=joints['jcr_strut_lca_uni'].jacobian_i(q)
	 jac_df.loc['jcr_strut_lca_uni','rbr_lca']=joints['jcr_strut_lca_uni'].jacobian_j(q)
	 jac_df.loc['jcr_tie_chassis','rbr_tie_rod']=joints['jcr_tie_chassis'].jacobian_i(q)
	 jac_df.loc['jcr_tie_chassis','rbs_chassis']=joints['jcr_tie_chassis'].jacobian_j(q)
	 jac_df.loc['jcr_tie_upright','rbr_tie_rod']=joints['jcr_tie_upright'].jacobian_i(q)
	 jac_df.loc['jcr_tie_upright','rbr_upright']=joints['jcr_tie_upright'].jacobian_j(q)
	 jac_df.loc['jcr_uca_ch','rbr_uca']=joints['jcr_uca_ch'].jacobian_i(q)
	 jac_df.loc['jcr_uca_ch','rbs_chassis']=joints['jcr_uca_ch'].jacobian_j(q)
	 jac_df.loc['jcr_uca_upright','rbr_uca']=joints['jcr_uca_upright'].jacobian_i(q)
	 jac_df.loc['jcr_uca_upright','rbr_upright']=joints['jcr_uca_upright'].jacobian_j(q)
	 jac_df.loc['rbl_lca','rbl_lca']=bodies['rbl_lca'].unity_jacobian(q)
	 jac_df.loc['rbl_strut_lower','rbl_strut_lower']=bodies['rbl_strut_lower'].unity_jacobian(q)
	 jac_df.loc['rbl_strut_upper','rbl_strut_upper']=bodies['rbl_strut_upper'].unity_jacobian(q)
	 jac_df.loc['rbl_tie_rod','rbl_tie_rod']=bodies['rbl_tie_rod'].unity_jacobian(q)
	 jac_df.loc['rbl_uca','rbl_uca']=bodies['rbl_uca'].unity_jacobian(q)
	 jac_df.loc['rbl_upright','rbl_upright']=bodies['rbl_upright'].unity_jacobian(q)
	 jac_df.loc['rbl_wheel_hub','rbl_wheel_hub']=bodies['rbl_wheel_hub'].unity_jacobian(q)
	 jac_df.loc['rbr_lca','rbr_lca']=bodies['rbr_lca'].unity_jacobian(q)
	 jac_df.loc['rbr_strut_lower','rbr_strut_lower']=bodies['rbr_strut_lower'].unity_jacobian(q)
	 jac_df.loc['rbr_strut_upper','rbr_strut_upper']=bodies['rbr_strut_upper'].unity_jacobian(q)
	 jac_df.loc['rbr_tie_rod','rbr_tie_rod']=bodies['rbr_tie_rod'].unity_jacobian(q)
	 jac_df.loc['rbr_uca','rbr_uca']=bodies['rbr_uca'].unity_jacobian(q)
	 jac_df.loc['rbr_upright','rbr_upright']=bodies['rbr_upright'].unity_jacobian(q)
	 jac_df.loc['rbr_wheel_hub','rbr_wheel_hub']=bodies['rbr_wheel_hub'].unity_jacobian(q)
	 jac_df.loc['rbs_chassis','rbs_chassis']=bodies['rbs_chassis'].mount_jacobian(q)
	 jac_df.loc['mcl_rotational_lock','rbl_upright']=actuators['mcl_rotational_lock'].jacobian_i(q)
	 jac_df.loc['mcl_rotational_lock','rbl_wheel_hub']=actuators['mcl_rotational_lock'].jacobian_j(q)
	 jac_df.loc['mcr_rotational_lock','rbr_upright']=actuators['mcr_rotational_lock'].jacobian_i(q)
	 jac_df.loc['mcr_rotational_lock','rbr_wheel_hub']=actuators['mcr_rotational_lock'].jacobian_j(q)
	 jac_df.loc['mcl_vertical','rbl_wheel_hub']=actuators['mcl_vertical'].jacobian()
	 jac_df.loc['mcr_vertical','rbr_wheel_hub']=actuators['mcr_vertical'].jacobian()
	 jac=sparse.bmat(jac_df,format='csc') 
	 return jac 


eq_s=pd.Series([39 *[None]],index=['jcl_hub_bearing', 'jcl_lca_ch', 'jcl_lca_upright', 'jcl_strut_chassis_uni', 'jcl_strut_cyl', 'jcl_strut_lca_uni', 'jcl_tie_chassis', 'jcl_tie_upright', 'jcl_uca_ch', 'jcl_uca_upright', 'jcr_hub_bearing', 'jcr_lca_ch', 'jcr_lca_upright', 'jcr_strut_chassis_uni', 'jcr_strut_cyl', 'jcr_strut_lca_uni', 'jcr_tie_chassis', 'jcr_tie_upright', 'jcr_uca_ch', 'jcr_uca_upright', 'rbl_lca', 'rbl_strut_lower', 'rbl_strut_upper', 'rbl_tie_rod', 'rbl_uca', 'rbl_upright', 'rbl_wheel_hub', 'rbr_lca', 'rbr_strut_lower', 'rbr_strut_upper', 'rbr_tie_rod', 'rbr_uca', 'rbr_upright', 'rbr_wheel_hub', 'rbs_chassis', 'mcl_rotational_lock', 'mcr_rotational_lock', 'mcl_vertical', 'mcr_vertical'])
def eq(q,bodies,joints,actuators): 
	 eq_s['jcl_hub_bearing']=joints['jcl_hub_bearing'].equations(q)
	 eq_s['jcl_lca_ch']=joints['jcl_lca_ch'].equations(q)
	 eq_s['jcl_lca_upright']=joints['jcl_lca_upright'].equations(q)
	 eq_s['jcl_strut_chassis_uni']=joints['jcl_strut_chassis_uni'].equations(q)
	 eq_s['jcl_strut_cyl']=joints['jcl_strut_cyl'].equations(q)
	 eq_s['jcl_strut_lca_uni']=joints['jcl_strut_lca_uni'].equations(q)
	 eq_s['jcl_tie_chassis']=joints['jcl_tie_chassis'].equations(q)
	 eq_s['jcl_tie_upright']=joints['jcl_tie_upright'].equations(q)
	 eq_s['jcl_uca_ch']=joints['jcl_uca_ch'].equations(q)
	 eq_s['jcl_uca_upright']=joints['jcl_uca_upright'].equations(q)
	 eq_s['jcr_hub_bearing']=joints['jcr_hub_bearing'].equations(q)
	 eq_s['jcr_lca_ch']=joints['jcr_lca_ch'].equations(q)
	 eq_s['jcr_lca_upright']=joints['jcr_lca_upright'].equations(q)
	 eq_s['jcr_strut_chassis_uni']=joints['jcr_strut_chassis_uni'].equations(q)
	 eq_s['jcr_strut_cyl']=joints['jcr_strut_cyl'].equations(q)
	 eq_s['jcr_strut_lca_uni']=joints['jcr_strut_lca_uni'].equations(q)
	 eq_s['jcr_tie_chassis']=joints['jcr_tie_chassis'].equations(q)
	 eq_s['jcr_tie_upright']=joints['jcr_tie_upright'].equations(q)
	 eq_s['jcr_uca_ch']=joints['jcr_uca_ch'].equations(q)
	 eq_s['jcr_uca_upright']=joints['jcr_uca_upright'].equations(q)
	 eq_s['rbl_lca']=bodies['rbl_lca'].unity_equation(q)
	 eq_s['rbl_strut_lower']=bodies['rbl_strut_lower'].unity_equation(q)
	 eq_s['rbl_strut_upper']=bodies['rbl_strut_upper'].unity_equation(q)
	 eq_s['rbl_tie_rod']=bodies['rbl_tie_rod'].unity_equation(q)
	 eq_s['rbl_uca']=bodies['rbl_uca'].unity_equation(q)
	 eq_s['rbl_upright']=bodies['rbl_upright'].unity_equation(q)
	 eq_s['rbl_wheel_hub']=bodies['rbl_wheel_hub'].unity_equation(q)
	 eq_s['rbr_lca']=bodies['rbr_lca'].unity_equation(q)
	 eq_s['rbr_strut_lower']=bodies['rbr_strut_lower'].unity_equation(q)
	 eq_s['rbr_strut_upper']=bodies['rbr_strut_upper'].unity_equation(q)
	 eq_s['rbr_tie_rod']=bodies['rbr_tie_rod'].unity_equation(q)
	 eq_s['rbr_uca']=bodies['rbr_uca'].unity_equation(q)
	 eq_s['rbr_upright']=bodies['rbr_upright'].unity_equation(q)
	 eq_s['rbr_wheel_hub']=bodies['rbr_wheel_hub'].unity_equation(q)
	 eq_s['rbs_chassis']=bodies['rbs_chassis'].mount_equation(q)
	 eq_s['mcl_rotational_lock']=actuators['mcl_rotational_lock'].equations(q)
	 eq_s['mcr_rotational_lock']=actuators['mcr_rotational_lock'].equations(q)
	 eq_s['mcl_vertical']=actuators['mcl_vertical'].equations(q)
	 eq_s['mcr_vertical']=actuators['mcr_vertical'].equations(q)
	 system=sparse.bmat(eq_s.values.reshape((39,1)),format='csc') 
	 return system.A.reshape((105,)) 


vel_rhs_s=pd.Series([39 *[None]],index=['jcl_hub_bearing', 'jcl_lca_ch', 'jcl_lca_upright', 'jcl_strut_chassis_uni', 'jcl_strut_cyl', 'jcl_strut_lca_uni', 'jcl_tie_chassis', 'jcl_tie_upright', 'jcl_uca_ch', 'jcl_uca_upright', 'jcr_hub_bearing', 'jcr_lca_ch', 'jcr_lca_upright', 'jcr_strut_chassis_uni', 'jcr_strut_cyl', 'jcr_strut_lca_uni', 'jcr_tie_chassis', 'jcr_tie_upright', 'jcr_uca_ch', 'jcr_uca_upright', 'rbl_lca', 'rbl_strut_lower', 'rbl_strut_upper', 'rbl_tie_rod', 'rbl_uca', 'rbl_upright', 'rbl_wheel_hub', 'rbr_lca', 'rbr_strut_lower', 'rbr_strut_upper', 'rbr_tie_rod', 'rbr_uca', 'rbr_upright', 'rbr_wheel_hub', 'rbs_chassis', 'mcl_rotational_lock', 'mcr_rotational_lock', 'mcl_vertical', 'mcr_vertical'])
def vel_rhs(actuators): 
	 vrhs=np.zeros((101,1))
	 vrhs=np.concatenate([vrhs,actuators['mcl_rotational_lock'].vel_rhs()]) 
	 vrhs=np.concatenate([vrhs,actuators['mcr_rotational_lock'].vel_rhs()]) 
	 vrhs=np.concatenate([vrhs,actuators['mcl_vertical'].vel_rhs()]) 
	 vrhs=np.concatenate([vrhs,actuators['mcr_vertical'].vel_rhs()]) 
	 return vrhs 
acc_rhs_s=pd.Series([39 *[None]],index=['jcl_hub_bearing', 'jcl_lca_ch', 'jcl_lca_upright', 'jcl_strut_chassis_uni', 'jcl_strut_cyl', 'jcl_strut_lca_uni', 'jcl_tie_chassis', 'jcl_tie_upright', 'jcl_uca_ch', 'jcl_uca_upright', 'jcr_hub_bearing', 'jcr_lca_ch', 'jcr_lca_upright', 'jcr_strut_chassis_uni', 'jcr_strut_cyl', 'jcr_strut_lca_uni', 'jcr_tie_chassis', 'jcr_tie_upright', 'jcr_uca_ch', 'jcr_uca_upright', 'rbl_lca', 'rbl_strut_lower', 'rbl_strut_upper', 'rbl_tie_rod', 'rbl_uca', 'rbl_upright', 'rbl_wheel_hub', 'rbr_lca', 'rbr_strut_lower', 'rbr_strut_upper', 'rbr_tie_rod', 'rbr_uca', 'rbr_upright', 'rbr_wheel_hub', 'rbs_chassis', 'mcl_rotational_lock', 'mcr_rotational_lock', 'mcl_vertical', 'mcr_vertical'])
def acc_rhs(q,qdot,bodies,joints,actuators): 
	 acc_rhs_s['jcl_hub_bearing']=joints['jcl_hub_bearing'].acc_rhs(q,qdot)
	 acc_rhs_s['jcl_lca_ch']=joints['jcl_lca_ch'].acc_rhs(q,qdot)
	 acc_rhs_s['jcl_lca_upright']=joints['jcl_lca_upright'].acc_rhs(q,qdot)
	 acc_rhs_s['jcl_strut_chassis_uni']=joints['jcl_strut_chassis_uni'].acc_rhs(q,qdot)
	 acc_rhs_s['jcl_strut_cyl']=joints['jcl_strut_cyl'].acc_rhs(q,qdot)
	 acc_rhs_s['jcl_strut_lca_uni']=joints['jcl_strut_lca_uni'].acc_rhs(q,qdot)
	 acc_rhs_s['jcl_tie_chassis']=joints['jcl_tie_chassis'].acc_rhs(q,qdot)
	 acc_rhs_s['jcl_tie_upright']=joints['jcl_tie_upright'].acc_rhs(q,qdot)
	 acc_rhs_s['jcl_uca_ch']=joints['jcl_uca_ch'].acc_rhs(q,qdot)
	 acc_rhs_s['jcl_uca_upright']=joints['jcl_uca_upright'].acc_rhs(q,qdot)
	 acc_rhs_s['jcr_hub_bearing']=joints['jcr_hub_bearing'].acc_rhs(q,qdot)
	 acc_rhs_s['jcr_lca_ch']=joints['jcr_lca_ch'].acc_rhs(q,qdot)
	 acc_rhs_s['jcr_lca_upright']=joints['jcr_lca_upright'].acc_rhs(q,qdot)
	 acc_rhs_s['jcr_strut_chassis_uni']=joints['jcr_strut_chassis_uni'].acc_rhs(q,qdot)
	 acc_rhs_s['jcr_strut_cyl']=joints['jcr_strut_cyl'].acc_rhs(q,qdot)
	 acc_rhs_s['jcr_strut_lca_uni']=joints['jcr_strut_lca_uni'].acc_rhs(q,qdot)
	 acc_rhs_s['jcr_tie_chassis']=joints['jcr_tie_chassis'].acc_rhs(q,qdot)
	 acc_rhs_s['jcr_tie_upright']=joints['jcr_tie_upright'].acc_rhs(q,qdot)
	 acc_rhs_s['jcr_uca_ch']=joints['jcr_uca_ch'].acc_rhs(q,qdot)
	 acc_rhs_s['jcr_uca_upright']=joints['jcr_uca_upright'].acc_rhs(q,qdot)
	 acc_rhs_s['rbl_lca']=bodies['rbl_lca'].acc_rhs(qdot)
	 acc_rhs_s['rbl_strut_lower']=bodies['rbl_strut_lower'].acc_rhs(qdot)
	 acc_rhs_s['rbl_strut_upper']=bodies['rbl_strut_upper'].acc_rhs(qdot)
	 acc_rhs_s['rbl_tie_rod']=bodies['rbl_tie_rod'].acc_rhs(qdot)
	 acc_rhs_s['rbl_uca']=bodies['rbl_uca'].acc_rhs(qdot)
	 acc_rhs_s['rbl_upright']=bodies['rbl_upright'].acc_rhs(qdot)
	 acc_rhs_s['rbl_wheel_hub']=bodies['rbl_wheel_hub'].acc_rhs(qdot)
	 acc_rhs_s['rbr_lca']=bodies['rbr_lca'].acc_rhs(qdot)
	 acc_rhs_s['rbr_strut_lower']=bodies['rbr_strut_lower'].acc_rhs(qdot)
	 acc_rhs_s['rbr_strut_upper']=bodies['rbr_strut_upper'].acc_rhs(qdot)
	 acc_rhs_s['rbr_tie_rod']=bodies['rbr_tie_rod'].acc_rhs(qdot)
	 acc_rhs_s['rbr_uca']=bodies['rbr_uca'].acc_rhs(qdot)
	 acc_rhs_s['rbr_upright']=bodies['rbr_upright'].acc_rhs(qdot)
	 acc_rhs_s['rbr_wheel_hub']=bodies['rbr_wheel_hub'].acc_rhs(qdot)
	 acc_rhs_s['rbs_chassis']=bodies['rbs_chassis'].mount_acc_rhs(qdot)
	 acc_rhs_s['mcl_rotational_lock']=actuators['mcl_rotational_lock'].acc_rhs(q,qdot)
	 acc_rhs_s['mcr_rotational_lock']=actuators['mcr_rotational_lock'].acc_rhs(q,qdot)
	 acc_rhs_s['mcl_vertical']=actuators['mcl_vertical'].acc_rhs(q,qdot)
	 acc_rhs_s['mcr_vertical']=actuators['mcr_vertical'].acc_rhs(q,qdot)
	 system=sparse.bmat(acc_rhs_s.values.reshape((39,1)),format='csc') 
	 return system.A.reshape((105,)) 


mass_matrix_df=pd.DataFrame([15 *[None]],columns=['rbl_lca', 'rbl_strut_lower', 'rbl_strut_upper', 'rbl_tie_rod', 'rbl_uca', 'rbl_upright', 'rbl_wheel_hub', 'rbr_lca', 'rbr_strut_lower', 'rbr_strut_upper', 'rbr_tie_rod', 'rbr_uca', 'rbr_upright', 'rbr_wheel_hub', 'rbs_chassis'],index=['rbl_lca', 'rbl_strut_lower', 'rbl_strut_upper', 'rbl_tie_rod', 'rbl_uca', 'rbl_upright', 'rbl_wheel_hub', 'rbr_lca', 'rbr_strut_lower', 'rbr_strut_upper', 'rbr_tie_rod', 'rbr_uca', 'rbr_upright', 'rbr_wheel_hub', 'rbs_chassis'])
def mass_matrix(q,bodies): 
	 mass_matrix_df.loc['rbl_lca','rbl_lca']=bodies['rbl_lca'].mass_matrix(q)
	 mass_matrix_df.loc['rbl_strut_lower','rbl_strut_lower']=bodies['rbl_strut_lower'].mass_matrix(q)
	 mass_matrix_df.loc['rbl_strut_upper','rbl_strut_upper']=bodies['rbl_strut_upper'].mass_matrix(q)
	 mass_matrix_df.loc['rbl_tie_rod','rbl_tie_rod']=bodies['rbl_tie_rod'].mass_matrix(q)
	 mass_matrix_df.loc['rbl_uca','rbl_uca']=bodies['rbl_uca'].mass_matrix(q)
	 mass_matrix_df.loc['rbl_upright','rbl_upright']=bodies['rbl_upright'].mass_matrix(q)
	 mass_matrix_df.loc['rbl_wheel_hub','rbl_wheel_hub']=bodies['rbl_wheel_hub'].mass_matrix(q)
	 mass_matrix_df.loc['rbr_lca','rbr_lca']=bodies['rbr_lca'].mass_matrix(q)
	 mass_matrix_df.loc['rbr_strut_lower','rbr_strut_lower']=bodies['rbr_strut_lower'].mass_matrix(q)
	 mass_matrix_df.loc['rbr_strut_upper','rbr_strut_upper']=bodies['rbr_strut_upper'].mass_matrix(q)
	 mass_matrix_df.loc['rbr_tie_rod','rbr_tie_rod']=bodies['rbr_tie_rod'].mass_matrix(q)
	 mass_matrix_df.loc['rbr_uca','rbr_uca']=bodies['rbr_uca'].mass_matrix(q)
	 mass_matrix_df.loc['rbr_upright','rbr_upright']=bodies['rbr_upright'].mass_matrix(q)
	 mass_matrix_df.loc['rbr_wheel_hub','rbr_wheel_hub']=bodies['rbr_wheel_hub'].mass_matrix(q)
	 mass_matrix_df.loc['rbs_chassis','rbs_chassis']=bodies['rbs_chassis'].mass_matrix(q)
	 mass_matrix=sparse.bmat(mass_matrix_df,format='csc') 
	 return mass_matrix 


Qg_s=pd.Series([15 *np.zeros((7,1))],index=['rbl_lca', 'rbl_strut_lower', 'rbl_strut_upper', 'rbl_tie_rod', 'rbl_uca', 'rbl_upright', 'rbl_wheel_hub', 'rbr_lca', 'rbr_strut_lower', 'rbr_strut_upper', 'rbr_tie_rod', 'rbr_uca', 'rbr_upright', 'rbr_wheel_hub', 'rbs_chassis'])
def Qg(bodies): 
	 Qg_s['rbl_lca']=bodies['rbl_lca'].gravity()
	 Qg_s['rbl_strut_lower']=bodies['rbl_strut_lower'].gravity()
	 Qg_s['rbl_strut_upper']=bodies['rbl_strut_upper'].gravity()
	 Qg_s['rbl_tie_rod']=bodies['rbl_tie_rod'].gravity()
	 Qg_s['rbl_uca']=bodies['rbl_uca'].gravity()
	 Qg_s['rbl_upright']=bodies['rbl_upright'].gravity()
	 Qg_s['rbl_wheel_hub']=bodies['rbl_wheel_hub'].gravity()
	 Qg_s['rbr_lca']=bodies['rbr_lca'].gravity()
	 Qg_s['rbr_strut_lower']=bodies['rbr_strut_lower'].gravity()
	 Qg_s['rbr_strut_upper']=bodies['rbr_strut_upper'].gravity()
	 Qg_s['rbr_tie_rod']=bodies['rbr_tie_rod'].gravity()
	 Qg_s['rbr_uca']=bodies['rbr_uca'].gravity()
	 Qg_s['rbr_upright']=bodies['rbr_upright'].gravity()
	 Qg_s['rbr_wheel_hub']=bodies['rbr_wheel_hub'].gravity()
	 Qg_s['rbs_chassis']=bodies['rbs_chassis'].gravity()
	 system=sparse.bmat(Qg_s.values.reshape((15,1)),format='csc') 
	 return system.A.reshape((105,)) 


Qv_s=pd.Series([15 *np.zeros((7,1))],index=['rbl_lca', 'rbl_strut_lower', 'rbl_strut_upper', 'rbl_tie_rod', 'rbl_uca', 'rbl_upright', 'rbl_wheel_hub', 'rbr_lca', 'rbr_strut_lower', 'rbr_strut_upper', 'rbr_tie_rod', 'rbr_uca', 'rbr_upright', 'rbr_wheel_hub', 'rbs_chassis'])
def Qv(bodies,q,qdot): 
	 Qv_s['rbl_lca']=bodies['rbl_lca'].centrifugal(q,qdot)
	 Qv_s['rbl_strut_lower']=bodies['rbl_strut_lower'].centrifugal(q,qdot)
	 Qv_s['rbl_strut_upper']=bodies['rbl_strut_upper'].centrifugal(q,qdot)
	 Qv_s['rbl_tie_rod']=bodies['rbl_tie_rod'].centrifugal(q,qdot)
	 Qv_s['rbl_uca']=bodies['rbl_uca'].centrifugal(q,qdot)
	 Qv_s['rbl_upright']=bodies['rbl_upright'].centrifugal(q,qdot)
	 Qv_s['rbl_wheel_hub']=bodies['rbl_wheel_hub'].centrifugal(q,qdot)
	 Qv_s['rbr_lca']=bodies['rbr_lca'].centrifugal(q,qdot)
	 Qv_s['rbr_strut_lower']=bodies['rbr_strut_lower'].centrifugal(q,qdot)
	 Qv_s['rbr_strut_upper']=bodies['rbr_strut_upper'].centrifugal(q,qdot)
	 Qv_s['rbr_tie_rod']=bodies['rbr_tie_rod'].centrifugal(q,qdot)
	 Qv_s['rbr_uca']=bodies['rbr_uca'].centrifugal(q,qdot)
	 Qv_s['rbr_upright']=bodies['rbr_upright'].centrifugal(q,qdot)
	 Qv_s['rbr_wheel_hub']=bodies['rbr_wheel_hub'].centrifugal(q,qdot)
	 Qv_s['rbs_chassis']=bodies['rbs_chassis'].centrifugal(q,qdot)
	 system=sparse.bmat(Qv_s.values.reshape((15,1)),format='csc') 
	 return system.A.reshape((105,)) 


Qa_s=pd.Series([15 *np.zeros((7,1))],index=['rbl_lca', 'rbl_strut_lower', 'rbl_strut_upper', 'rbl_tie_rod', 'rbl_uca', 'rbl_upright', 'rbl_wheel_hub', 'rbr_lca', 'rbr_strut_lower', 'rbr_strut_upper', 'rbr_tie_rod', 'rbr_uca', 'rbr_upright', 'rbr_wheel_hub', 'rbs_chassis'])
def Qa(forces,q,qdot): 
	 Qi,Qj=forces['fel_air_struts'].equation(q,qdot) 
	 Qa_s['rbl_strut_upper']=Qi
	 Qa_s['rbl_strut_lower']=Qj
	 Qi,Qj=forces['fer_air_struts'].equation(q,qdot) 
	 Qa_s['rbr_strut_upper']=Qi
	 Qa_s['rbr_strut_lower']=Qj
	 system=sparse.bmat(Qa_s.values.reshape((15,1)),format='csc') 
	 return system.A.reshape((105,)) 


JR_s=pd.Series(np.zeros((120)),index=['jcl_hub_bearing_Fx', 'jcl_hub_bearing_Fy', 'jcl_hub_bearing_Fz', 'jcl_hub_bearing_Mx', 'jcl_hub_bearing_My', 'jcl_hub_bearing_Mz', 'jcl_lca_ch_Fx', 'jcl_lca_ch_Fy', 'jcl_lca_ch_Fz', 'jcl_lca_ch_Mx', 'jcl_lca_ch_My', 'jcl_lca_ch_Mz', 'jcl_lca_upright_Fx', 'jcl_lca_upright_Fy', 'jcl_lca_upright_Fz', 'jcl_lca_upright_Mx', 'jcl_lca_upright_My', 'jcl_lca_upright_Mz', 'jcl_strut_chassis_uni_Fx', 'jcl_strut_chassis_uni_Fy', 'jcl_strut_chassis_uni_Fz', 'jcl_strut_chassis_uni_Mx', 'jcl_strut_chassis_uni_My', 'jcl_strut_chassis_uni_Mz', 'jcl_strut_cyl_Fx', 'jcl_strut_cyl_Fy', 'jcl_strut_cyl_Fz', 'jcl_strut_cyl_Mx', 'jcl_strut_cyl_My', 'jcl_strut_cyl_Mz', 'jcl_strut_lca_uni_Fx', 'jcl_strut_lca_uni_Fy', 'jcl_strut_lca_uni_Fz', 'jcl_strut_lca_uni_Mx', 'jcl_strut_lca_uni_My', 'jcl_strut_lca_uni_Mz', 'jcl_tie_chassis_Fx', 'jcl_tie_chassis_Fy', 'jcl_tie_chassis_Fz', 'jcl_tie_chassis_Mx', 'jcl_tie_chassis_My', 'jcl_tie_chassis_Mz', 'jcl_tie_upright_Fx', 'jcl_tie_upright_Fy', 'jcl_tie_upright_Fz', 'jcl_tie_upright_Mx', 'jcl_tie_upright_My', 'jcl_tie_upright_Mz', 'jcl_uca_ch_Fx', 'jcl_uca_ch_Fy', 'jcl_uca_ch_Fz', 'jcl_uca_ch_Mx', 'jcl_uca_ch_My', 'jcl_uca_ch_Mz', 'jcl_uca_upright_Fx', 'jcl_uca_upright_Fy', 'jcl_uca_upright_Fz', 'jcl_uca_upright_Mx', 'jcl_uca_upright_My', 'jcl_uca_upright_Mz', 'jcr_hub_bearing_Fx', 'jcr_hub_bearing_Fy', 'jcr_hub_bearing_Fz', 'jcr_hub_bearing_Mx', 'jcr_hub_bearing_My', 'jcr_hub_bearing_Mz', 'jcr_lca_ch_Fx', 'jcr_lca_ch_Fy', 'jcr_lca_ch_Fz', 'jcr_lca_ch_Mx', 'jcr_lca_ch_My', 'jcr_lca_ch_Mz', 'jcr_lca_upright_Fx', 'jcr_lca_upright_Fy', 'jcr_lca_upright_Fz', 'jcr_lca_upright_Mx', 'jcr_lca_upright_My', 'jcr_lca_upright_Mz', 'jcr_strut_chassis_uni_Fx', 'jcr_strut_chassis_uni_Fy', 'jcr_strut_chassis_uni_Fz', 'jcr_strut_chassis_uni_Mx', 'jcr_strut_chassis_uni_My', 'jcr_strut_chassis_uni_Mz', 'jcr_strut_cyl_Fx', 'jcr_strut_cyl_Fy', 'jcr_strut_cyl_Fz', 'jcr_strut_cyl_Mx', 'jcr_strut_cyl_My', 'jcr_strut_cyl_Mz', 'jcr_strut_lca_uni_Fx', 'jcr_strut_lca_uni_Fy', 'jcr_strut_lca_uni_Fz', 'jcr_strut_lca_uni_Mx', 'jcr_strut_lca_uni_My', 'jcr_strut_lca_uni_Mz', 'jcr_tie_chassis_Fx', 'jcr_tie_chassis_Fy', 'jcr_tie_chassis_Fz', 'jcr_tie_chassis_Mx', 'jcr_tie_chassis_My', 'jcr_tie_chassis_Mz', 'jcr_tie_upright_Fx', 'jcr_tie_upright_Fy', 'jcr_tie_upright_Fz', 'jcr_tie_upright_Mx', 'jcr_tie_upright_My', 'jcr_tie_upright_Mz', 'jcr_uca_ch_Fx', 'jcr_uca_ch_Fy', 'jcr_uca_ch_Fz', 'jcr_uca_ch_Mx', 'jcr_uca_ch_My', 'jcr_uca_ch_Mz', 'jcr_uca_upright_Fx', 'jcr_uca_upright_Fy', 'jcr_uca_upright_Fz', 'jcr_uca_upright_Mx', 'jcr_uca_upright_My', 'jcr_uca_upright_Mz'])
def JR(joints,q,lamda): 
	 JR_s[['jcl_hub_bearing_Fx', 'jcl_hub_bearing_Fy', 'jcl_hub_bearing_Fz', 'jcl_hub_bearing_Mx', 'jcl_hub_bearing_My', 'jcl_hub_bearing_Mz']]=joints['jcl_hub_bearing'].reactions(q,lamda)
	 JR_s[['jcl_lca_ch_Fx', 'jcl_lca_ch_Fy', 'jcl_lca_ch_Fz', 'jcl_lca_ch_Mx', 'jcl_lca_ch_My', 'jcl_lca_ch_Mz']]=joints['jcl_lca_ch'].reactions(q,lamda)
	 JR_s[['jcl_lca_upright_Fx', 'jcl_lca_upright_Fy', 'jcl_lca_upright_Fz', 'jcl_lca_upright_Mx', 'jcl_lca_upright_My', 'jcl_lca_upright_Mz']]=joints['jcl_lca_upright'].reactions(q,lamda)
	 JR_s[['jcl_strut_chassis_uni_Fx', 'jcl_strut_chassis_uni_Fy', 'jcl_strut_chassis_uni_Fz', 'jcl_strut_chassis_uni_Mx', 'jcl_strut_chassis_uni_My', 'jcl_strut_chassis_uni_Mz']]=joints['jcl_strut_chassis_uni'].reactions(q,lamda)
	 JR_s[['jcl_strut_cyl_Fx', 'jcl_strut_cyl_Fy', 'jcl_strut_cyl_Fz', 'jcl_strut_cyl_Mx', 'jcl_strut_cyl_My', 'jcl_strut_cyl_Mz']]=joints['jcl_strut_cyl'].reactions(q,lamda)
	 JR_s[['jcl_strut_lca_uni_Fx', 'jcl_strut_lca_uni_Fy', 'jcl_strut_lca_uni_Fz', 'jcl_strut_lca_uni_Mx', 'jcl_strut_lca_uni_My', 'jcl_strut_lca_uni_Mz']]=joints['jcl_strut_lca_uni'].reactions(q,lamda)
	 JR_s[['jcl_tie_chassis_Fx', 'jcl_tie_chassis_Fy', 'jcl_tie_chassis_Fz', 'jcl_tie_chassis_Mx', 'jcl_tie_chassis_My', 'jcl_tie_chassis_Mz']]=joints['jcl_tie_chassis'].reactions(q,lamda)
	 JR_s[['jcl_tie_upright_Fx', 'jcl_tie_upright_Fy', 'jcl_tie_upright_Fz', 'jcl_tie_upright_Mx', 'jcl_tie_upright_My', 'jcl_tie_upright_Mz']]=joints['jcl_tie_upright'].reactions(q,lamda)
	 JR_s[['jcl_uca_ch_Fx', 'jcl_uca_ch_Fy', 'jcl_uca_ch_Fz', 'jcl_uca_ch_Mx', 'jcl_uca_ch_My', 'jcl_uca_ch_Mz']]=joints['jcl_uca_ch'].reactions(q,lamda)
	 JR_s[['jcl_uca_upright_Fx', 'jcl_uca_upright_Fy', 'jcl_uca_upright_Fz', 'jcl_uca_upright_Mx', 'jcl_uca_upright_My', 'jcl_uca_upright_Mz']]=joints['jcl_uca_upright'].reactions(q,lamda)
	 JR_s[['jcr_hub_bearing_Fx', 'jcr_hub_bearing_Fy', 'jcr_hub_bearing_Fz', 'jcr_hub_bearing_Mx', 'jcr_hub_bearing_My', 'jcr_hub_bearing_Mz']]=joints['jcr_hub_bearing'].reactions(q,lamda)
	 JR_s[['jcr_lca_ch_Fx', 'jcr_lca_ch_Fy', 'jcr_lca_ch_Fz', 'jcr_lca_ch_Mx', 'jcr_lca_ch_My', 'jcr_lca_ch_Mz']]=joints['jcr_lca_ch'].reactions(q,lamda)
	 JR_s[['jcr_lca_upright_Fx', 'jcr_lca_upright_Fy', 'jcr_lca_upright_Fz', 'jcr_lca_upright_Mx', 'jcr_lca_upright_My', 'jcr_lca_upright_Mz']]=joints['jcr_lca_upright'].reactions(q,lamda)
	 JR_s[['jcr_strut_chassis_uni_Fx', 'jcr_strut_chassis_uni_Fy', 'jcr_strut_chassis_uni_Fz', 'jcr_strut_chassis_uni_Mx', 'jcr_strut_chassis_uni_My', 'jcr_strut_chassis_uni_Mz']]=joints['jcr_strut_chassis_uni'].reactions(q,lamda)
	 JR_s[['jcr_strut_cyl_Fx', 'jcr_strut_cyl_Fy', 'jcr_strut_cyl_Fz', 'jcr_strut_cyl_Mx', 'jcr_strut_cyl_My', 'jcr_strut_cyl_Mz']]=joints['jcr_strut_cyl'].reactions(q,lamda)
	 JR_s[['jcr_strut_lca_uni_Fx', 'jcr_strut_lca_uni_Fy', 'jcr_strut_lca_uni_Fz', 'jcr_strut_lca_uni_Mx', 'jcr_strut_lca_uni_My', 'jcr_strut_lca_uni_Mz']]=joints['jcr_strut_lca_uni'].reactions(q,lamda)
	 JR_s[['jcr_tie_chassis_Fx', 'jcr_tie_chassis_Fy', 'jcr_tie_chassis_Fz', 'jcr_tie_chassis_Mx', 'jcr_tie_chassis_My', 'jcr_tie_chassis_Mz']]=joints['jcr_tie_chassis'].reactions(q,lamda)
	 JR_s[['jcr_tie_upright_Fx', 'jcr_tie_upright_Fy', 'jcr_tie_upright_Fz', 'jcr_tie_upright_Mx', 'jcr_tie_upright_My', 'jcr_tie_upright_Mz']]=joints['jcr_tie_upright'].reactions(q,lamda)
	 JR_s[['jcr_uca_ch_Fx', 'jcr_uca_ch_Fy', 'jcr_uca_ch_Fz', 'jcr_uca_ch_Mx', 'jcr_uca_ch_My', 'jcr_uca_ch_Mz']]=joints['jcr_uca_ch'].reactions(q,lamda)
	 JR_s[['jcr_uca_upright_Fx', 'jcr_uca_upright_Fy', 'jcr_uca_upright_Fz', 'jcr_uca_upright_Mx', 'jcr_uca_upright_My', 'jcr_uca_upright_Mz']]=joints['jcr_uca_upright'].reactions(q,lamda)
	 return JR_s 


