import numpy as np 
import pandas as pd 
from scipy import sparse 


jac_df=pd.DataFrame([35 *[None]],columns=['chassis', 'ground', 'uca_rr', 'lca_rr', 'upright_rr', 'tie_rr', 'd1_rr', 'd2_rr', 'wheel_rr', 'uca_lr', 'lca_lr', 'upright_lr', 'tie_lr', 'd1_lr', 'd2_lr', 'wheel_lr', 'uca_rf', 'lca_rf', 'upright_rf', 'tie_rf', 'd1_rf', 'd2_rf', 'wheel_rf', 'uca_lf', 'lca_lf', 'upright_lf', 'tie_lf', 'd1_lf', 'd2_lf', 'wheel_lf', 'l1_rear', 'l2_rear', 'l3_rear', 'l4_rear', 'l5_rear'],index=['ucaf_lf_rev', 'lcaf_lf_rev', 'ucao_lf_sph', 'lcao_lf_sph', 'tro_lf_sph', 'ch_sh_lf_uni', 'sh_lca_lf_uni', 'tri_lf_uni', 'd_m_lf_cyl', 'wc_lf_rev', 'ucaf_rr_rev', 'lcaf_rr_rev', 'ucao_rr_sph', 'lcao_rr_sph', 'tro_rr_sph', 'ch_sh_rr_uni', 'sh_lca_rr_uni', 'tri_rr_uni', 'd_m_rr_cyl', 'wc_rr_rev', 'ucaf_rf_rev', 'lcaf_rf_rev', 'ucao_rf_sph', 'lcao_rf_sph', 'tro_rf_sph', 'ch_sh_rf_uni', 'sh_lca_rf_uni', 'tri_rf_uni', 'd_m_rf_cyl', 'wc_rf_rev', 'ucaf_lr_rev', 'lcaf_lr_rev', 'ucao_lr_sph', 'lcao_lr_sph', 'tro_lr_sph', 'ch_sh_lr_uni', 'sh_lca_lr_uni', 'tri_lr_uni', 'd_m_lr_cyl', 'wc_lr_rev', 'mount_1_rear_rev', 'mount_2_rear_rev', 'C1_rear_uni', 'E_rear_uni', 'F_rear_uni', 'C2_rear_sph', 'EF_rear_cyl', 'chassis', 'ground', 'uca_rr', 'lca_rr', 'upright_rr', 'tie_rr', 'd1_rr', 'd2_rr', 'wheel_rr', 'uca_lr', 'lca_lr', 'upright_lr', 'tie_lr', 'd1_lr', 'd2_lr', 'wheel_lr', 'uca_rf', 'lca_rf', 'upright_rf', 'tie_rf', 'd1_rf', 'd2_rf', 'wheel_rf', 'uca_lf', 'lca_lf', 'upright_lf', 'tie_lf', 'd1_lf', 'd2_lf', 'wheel_lf', 'l1_rear', 'l2_rear', 'l3_rear', 'l4_rear', 'l5_rear', 'wc_lf_rev_actuator', 'wc_rf_rev_actuator', 'wc_lr_rev_actuator', 'wc_rr_rev_actuator', 'l5_rear.y_actuator'])
def cq(q,bodies,joints,actuators): 
	 jac_df.loc['ucaf_lf_rev','uca_lf']=joints['ucaf_lf_rev'].jacobian_i(q)
	 jac_df.loc['ucaf_lf_rev','chassis']=joints['ucaf_lf_rev'].jacobian_j(q)
	 jac_df.loc['lcaf_lf_rev','lca_lf']=joints['lcaf_lf_rev'].jacobian_i(q)
	 jac_df.loc['lcaf_lf_rev','chassis']=joints['lcaf_lf_rev'].jacobian_j(q)
	 jac_df.loc['ucao_lf_sph','uca_lf']=joints['ucao_lf_sph'].jacobian_i(q)
	 jac_df.loc['ucao_lf_sph','upright_lf']=joints['ucao_lf_sph'].jacobian_j(q)
	 jac_df.loc['lcao_lf_sph','lca_lf']=joints['lcao_lf_sph'].jacobian_i(q)
	 jac_df.loc['lcao_lf_sph','upright_lf']=joints['lcao_lf_sph'].jacobian_j(q)
	 jac_df.loc['tro_lf_sph','tie_lf']=joints['tro_lf_sph'].jacobian_i(q)
	 jac_df.loc['tro_lf_sph','upright_lf']=joints['tro_lf_sph'].jacobian_j(q)
	 jac_df.loc['ch_sh_lf_uni','d2_lf']=joints['ch_sh_lf_uni'].jacobian_i(q)
	 jac_df.loc['ch_sh_lf_uni','chassis']=joints['ch_sh_lf_uni'].jacobian_j(q)
	 jac_df.loc['sh_lca_lf_uni','lca_lf']=joints['sh_lca_lf_uni'].jacobian_i(q)
	 jac_df.loc['sh_lca_lf_uni','d1_lf']=joints['sh_lca_lf_uni'].jacobian_j(q)
	 jac_df.loc['tri_lf_uni','chassis']=joints['tri_lf_uni'].jacobian_i(q)
	 jac_df.loc['tri_lf_uni','tie_lf']=joints['tri_lf_uni'].jacobian_j(q)
	 jac_df.loc['d_m_lf_cyl','d1_lf']=joints['d_m_lf_cyl'].jacobian_i(q)
	 jac_df.loc['d_m_lf_cyl','d2_lf']=joints['d_m_lf_cyl'].jacobian_j(q)
	 jac_df.loc['wc_lf_rev','wheel_lf']=joints['wc_lf_rev'].jacobian_i(q)
	 jac_df.loc['wc_lf_rev','upright_lf']=joints['wc_lf_rev'].jacobian_j(q)
	 jac_df.loc['ucaf_rr_rev','uca_rr']=joints['ucaf_rr_rev'].jacobian_i(q)
	 jac_df.loc['ucaf_rr_rev','chassis']=joints['ucaf_rr_rev'].jacobian_j(q)
	 jac_df.loc['lcaf_rr_rev','lca_rr']=joints['lcaf_rr_rev'].jacobian_i(q)
	 jac_df.loc['lcaf_rr_rev','chassis']=joints['lcaf_rr_rev'].jacobian_j(q)
	 jac_df.loc['ucao_rr_sph','uca_rr']=joints['ucao_rr_sph'].jacobian_i(q)
	 jac_df.loc['ucao_rr_sph','upright_rr']=joints['ucao_rr_sph'].jacobian_j(q)
	 jac_df.loc['lcao_rr_sph','lca_rr']=joints['lcao_rr_sph'].jacobian_i(q)
	 jac_df.loc['lcao_rr_sph','upright_rr']=joints['lcao_rr_sph'].jacobian_j(q)
	 jac_df.loc['tro_rr_sph','tie_rr']=joints['tro_rr_sph'].jacobian_i(q)
	 jac_df.loc['tro_rr_sph','upright_rr']=joints['tro_rr_sph'].jacobian_j(q)
	 jac_df.loc['ch_sh_rr_uni','d2_rr']=joints['ch_sh_rr_uni'].jacobian_i(q)
	 jac_df.loc['ch_sh_rr_uni','chassis']=joints['ch_sh_rr_uni'].jacobian_j(q)
	 jac_df.loc['sh_lca_rr_uni','lca_rr']=joints['sh_lca_rr_uni'].jacobian_i(q)
	 jac_df.loc['sh_lca_rr_uni','d1_rr']=joints['sh_lca_rr_uni'].jacobian_j(q)
	 jac_df.loc['tri_rr_uni','l1_rear']=joints['tri_rr_uni'].jacobian_i(q)
	 jac_df.loc['tri_rr_uni','tie_rr']=joints['tri_rr_uni'].jacobian_j(q)
	 jac_df.loc['d_m_rr_cyl','d1_rr']=joints['d_m_rr_cyl'].jacobian_i(q)
	 jac_df.loc['d_m_rr_cyl','d2_rr']=joints['d_m_rr_cyl'].jacobian_j(q)
	 jac_df.loc['wc_rr_rev','wheel_rr']=joints['wc_rr_rev'].jacobian_i(q)
	 jac_df.loc['wc_rr_rev','upright_rr']=joints['wc_rr_rev'].jacobian_j(q)
	 jac_df.loc['ucaf_rf_rev','uca_rf']=joints['ucaf_rf_rev'].jacobian_i(q)
	 jac_df.loc['ucaf_rf_rev','chassis']=joints['ucaf_rf_rev'].jacobian_j(q)
	 jac_df.loc['lcaf_rf_rev','lca_rf']=joints['lcaf_rf_rev'].jacobian_i(q)
	 jac_df.loc['lcaf_rf_rev','chassis']=joints['lcaf_rf_rev'].jacobian_j(q)
	 jac_df.loc['ucao_rf_sph','uca_rf']=joints['ucao_rf_sph'].jacobian_i(q)
	 jac_df.loc['ucao_rf_sph','upright_rf']=joints['ucao_rf_sph'].jacobian_j(q)
	 jac_df.loc['lcao_rf_sph','lca_rf']=joints['lcao_rf_sph'].jacobian_i(q)
	 jac_df.loc['lcao_rf_sph','upright_rf']=joints['lcao_rf_sph'].jacobian_j(q)
	 jac_df.loc['tro_rf_sph','tie_rf']=joints['tro_rf_sph'].jacobian_i(q)
	 jac_df.loc['tro_rf_sph','upright_rf']=joints['tro_rf_sph'].jacobian_j(q)
	 jac_df.loc['ch_sh_rf_uni','d2_rf']=joints['ch_sh_rf_uni'].jacobian_i(q)
	 jac_df.loc['ch_sh_rf_uni','chassis']=joints['ch_sh_rf_uni'].jacobian_j(q)
	 jac_df.loc['sh_lca_rf_uni','lca_rf']=joints['sh_lca_rf_uni'].jacobian_i(q)
	 jac_df.loc['sh_lca_rf_uni','d1_rf']=joints['sh_lca_rf_uni'].jacobian_j(q)
	 jac_df.loc['tri_rf_uni','chassis']=joints['tri_rf_uni'].jacobian_i(q)
	 jac_df.loc['tri_rf_uni','tie_rf']=joints['tri_rf_uni'].jacobian_j(q)
	 jac_df.loc['d_m_rf_cyl','d1_rf']=joints['d_m_rf_cyl'].jacobian_i(q)
	 jac_df.loc['d_m_rf_cyl','d2_rf']=joints['d_m_rf_cyl'].jacobian_j(q)
	 jac_df.loc['wc_rf_rev','wheel_rf']=joints['wc_rf_rev'].jacobian_i(q)
	 jac_df.loc['wc_rf_rev','upright_rf']=joints['wc_rf_rev'].jacobian_j(q)
	 jac_df.loc['ucaf_lr_rev','uca_lr']=joints['ucaf_lr_rev'].jacobian_i(q)
	 jac_df.loc['ucaf_lr_rev','chassis']=joints['ucaf_lr_rev'].jacobian_j(q)
	 jac_df.loc['lcaf_lr_rev','lca_lr']=joints['lcaf_lr_rev'].jacobian_i(q)
	 jac_df.loc['lcaf_lr_rev','chassis']=joints['lcaf_lr_rev'].jacobian_j(q)
	 jac_df.loc['ucao_lr_sph','uca_lr']=joints['ucao_lr_sph'].jacobian_i(q)
	 jac_df.loc['ucao_lr_sph','upright_lr']=joints['ucao_lr_sph'].jacobian_j(q)
	 jac_df.loc['lcao_lr_sph','lca_lr']=joints['lcao_lr_sph'].jacobian_i(q)
	 jac_df.loc['lcao_lr_sph','upright_lr']=joints['lcao_lr_sph'].jacobian_j(q)
	 jac_df.loc['tro_lr_sph','tie_lr']=joints['tro_lr_sph'].jacobian_i(q)
	 jac_df.loc['tro_lr_sph','upright_lr']=joints['tro_lr_sph'].jacobian_j(q)
	 jac_df.loc['ch_sh_lr_uni','d2_lr']=joints['ch_sh_lr_uni'].jacobian_i(q)
	 jac_df.loc['ch_sh_lr_uni','chassis']=joints['ch_sh_lr_uni'].jacobian_j(q)
	 jac_df.loc['sh_lca_lr_uni','lca_lr']=joints['sh_lca_lr_uni'].jacobian_i(q)
	 jac_df.loc['sh_lca_lr_uni','d1_lr']=joints['sh_lca_lr_uni'].jacobian_j(q)
	 jac_df.loc['tri_lr_uni','l3_rear']=joints['tri_lr_uni'].jacobian_i(q)
	 jac_df.loc['tri_lr_uni','tie_lr']=joints['tri_lr_uni'].jacobian_j(q)
	 jac_df.loc['d_m_lr_cyl','d1_lr']=joints['d_m_lr_cyl'].jacobian_i(q)
	 jac_df.loc['d_m_lr_cyl','d2_lr']=joints['d_m_lr_cyl'].jacobian_j(q)
	 jac_df.loc['wc_lr_rev','wheel_lr']=joints['wc_lr_rev'].jacobian_i(q)
	 jac_df.loc['wc_lr_rev','upright_lr']=joints['wc_lr_rev'].jacobian_j(q)
	 jac_df.loc['mount_1_rear_rev','l1_rear']=joints['mount_1_rear_rev'].jacobian_i(q)
	 jac_df.loc['mount_1_rear_rev','chassis']=joints['mount_1_rear_rev'].jacobian_j(q)
	 jac_df.loc['mount_2_rear_rev','l3_rear']=joints['mount_2_rear_rev'].jacobian_i(q)
	 jac_df.loc['mount_2_rear_rev','chassis']=joints['mount_2_rear_rev'].jacobian_j(q)
	 jac_df.loc['C1_rear_uni','l1_rear']=joints['C1_rear_uni'].jacobian_i(q)
	 jac_df.loc['C1_rear_uni','l2_rear']=joints['C1_rear_uni'].jacobian_j(q)
	 jac_df.loc['E_rear_uni','l4_rear']=joints['E_rear_uni'].jacobian_i(q)
	 jac_df.loc['E_rear_uni','chassis']=joints['E_rear_uni'].jacobian_j(q)
	 jac_df.loc['F_rear_uni','l5_rear']=joints['F_rear_uni'].jacobian_i(q)
	 jac_df.loc['F_rear_uni','l3_rear']=joints['F_rear_uni'].jacobian_j(q)
	 jac_df.loc['C2_rear_sph','l2_rear']=joints['C2_rear_sph'].jacobian_i(q)
	 jac_df.loc['C2_rear_sph','l3_rear']=joints['C2_rear_sph'].jacobian_j(q)
	 jac_df.loc['EF_rear_cyl','l4_rear']=joints['EF_rear_cyl'].jacobian_i(q)
	 jac_df.loc['EF_rear_cyl','l5_rear']=joints['EF_rear_cyl'].jacobian_j(q)
	 jac_df.loc['chassis','chassis']=bodies['chassis'].unity_jacobian(q)
	 jac_df.loc['ground','ground']=bodies['ground'].mount_jacobian(q)
	 jac_df.loc['uca_rr','uca_rr']=bodies['uca_rr'].unity_jacobian(q)
	 jac_df.loc['lca_rr','lca_rr']=bodies['lca_rr'].unity_jacobian(q)
	 jac_df.loc['upright_rr','upright_rr']=bodies['upright_rr'].unity_jacobian(q)
	 jac_df.loc['tie_rr','tie_rr']=bodies['tie_rr'].unity_jacobian(q)
	 jac_df.loc['d1_rr','d1_rr']=bodies['d1_rr'].unity_jacobian(q)
	 jac_df.loc['d2_rr','d2_rr']=bodies['d2_rr'].unity_jacobian(q)
	 jac_df.loc['wheel_rr','wheel_rr']=bodies['wheel_rr'].unity_jacobian(q)
	 jac_df.loc['uca_lr','uca_lr']=bodies['uca_lr'].unity_jacobian(q)
	 jac_df.loc['lca_lr','lca_lr']=bodies['lca_lr'].unity_jacobian(q)
	 jac_df.loc['upright_lr','upright_lr']=bodies['upright_lr'].unity_jacobian(q)
	 jac_df.loc['tie_lr','tie_lr']=bodies['tie_lr'].unity_jacobian(q)
	 jac_df.loc['d1_lr','d1_lr']=bodies['d1_lr'].unity_jacobian(q)
	 jac_df.loc['d2_lr','d2_lr']=bodies['d2_lr'].unity_jacobian(q)
	 jac_df.loc['wheel_lr','wheel_lr']=bodies['wheel_lr'].unity_jacobian(q)
	 jac_df.loc['uca_rf','uca_rf']=bodies['uca_rf'].unity_jacobian(q)
	 jac_df.loc['lca_rf','lca_rf']=bodies['lca_rf'].unity_jacobian(q)
	 jac_df.loc['upright_rf','upright_rf']=bodies['upright_rf'].unity_jacobian(q)
	 jac_df.loc['tie_rf','tie_rf']=bodies['tie_rf'].unity_jacobian(q)
	 jac_df.loc['d1_rf','d1_rf']=bodies['d1_rf'].unity_jacobian(q)
	 jac_df.loc['d2_rf','d2_rf']=bodies['d2_rf'].unity_jacobian(q)
	 jac_df.loc['wheel_rf','wheel_rf']=bodies['wheel_rf'].unity_jacobian(q)
	 jac_df.loc['uca_lf','uca_lf']=bodies['uca_lf'].unity_jacobian(q)
	 jac_df.loc['lca_lf','lca_lf']=bodies['lca_lf'].unity_jacobian(q)
	 jac_df.loc['upright_lf','upright_lf']=bodies['upright_lf'].unity_jacobian(q)
	 jac_df.loc['tie_lf','tie_lf']=bodies['tie_lf'].unity_jacobian(q)
	 jac_df.loc['d1_lf','d1_lf']=bodies['d1_lf'].unity_jacobian(q)
	 jac_df.loc['d2_lf','d2_lf']=bodies['d2_lf'].unity_jacobian(q)
	 jac_df.loc['wheel_lf','wheel_lf']=bodies['wheel_lf'].unity_jacobian(q)
	 jac_df.loc['l1_rear','l1_rear']=bodies['l1_rear'].unity_jacobian(q)
	 jac_df.loc['l2_rear','l2_rear']=bodies['l2_rear'].unity_jacobian(q)
	 jac_df.loc['l3_rear','l3_rear']=bodies['l3_rear'].unity_jacobian(q)
	 jac_df.loc['l4_rear','l4_rear']=bodies['l4_rear'].unity_jacobian(q)
	 jac_df.loc['l5_rear','l5_rear']=bodies['l5_rear'].unity_jacobian(q)
	 jac_df.loc['wc_lf_rev_actuator','wheel_lf']=actuators['wc_lf_rev_actuator'].jacobian_i(q)
	 jac_df.loc['wc_lf_rev_actuator','upright_lf']=actuators['wc_lf_rev_actuator'].jacobian_j(q)
	 jac_df.loc['wc_rf_rev_actuator','wheel_rf']=actuators['wc_rf_rev_actuator'].jacobian_i(q)
	 jac_df.loc['wc_rf_rev_actuator','upright_rf']=actuators['wc_rf_rev_actuator'].jacobian_j(q)
	 jac_df.loc['wc_lr_rev_actuator','wheel_lr']=actuators['wc_lr_rev_actuator'].jacobian_i(q)
	 jac_df.loc['wc_lr_rev_actuator','upright_lr']=actuators['wc_lr_rev_actuator'].jacobian_j(q)
	 jac_df.loc['wc_rr_rev_actuator','wheel_rr']=actuators['wc_rr_rev_actuator'].jacobian_i(q)
	 jac_df.loc['wc_rr_rev_actuator','upright_rr']=actuators['wc_rr_rev_actuator'].jacobian_j(q)
	 jac_df.loc['l5_rear.y_actuator','l5_rear']=actuators['l5_rear.y_actuator'].jacobian()
	 jac=sparse.bmat(jac_df,format='csc') 
	 return jac 


eq_s=pd.Series([87 *[None]],index=['ucaf_lf_rev', 'lcaf_lf_rev', 'ucao_lf_sph', 'lcao_lf_sph', 'tro_lf_sph', 'ch_sh_lf_uni', 'sh_lca_lf_uni', 'tri_lf_uni', 'd_m_lf_cyl', 'wc_lf_rev', 'ucaf_rr_rev', 'lcaf_rr_rev', 'ucao_rr_sph', 'lcao_rr_sph', 'tro_rr_sph', 'ch_sh_rr_uni', 'sh_lca_rr_uni', 'tri_rr_uni', 'd_m_rr_cyl', 'wc_rr_rev', 'ucaf_rf_rev', 'lcaf_rf_rev', 'ucao_rf_sph', 'lcao_rf_sph', 'tro_rf_sph', 'ch_sh_rf_uni', 'sh_lca_rf_uni', 'tri_rf_uni', 'd_m_rf_cyl', 'wc_rf_rev', 'ucaf_lr_rev', 'lcaf_lr_rev', 'ucao_lr_sph', 'lcao_lr_sph', 'tro_lr_sph', 'ch_sh_lr_uni', 'sh_lca_lr_uni', 'tri_lr_uni', 'd_m_lr_cyl', 'wc_lr_rev', 'mount_1_rear_rev', 'mount_2_rear_rev', 'C1_rear_uni', 'E_rear_uni', 'F_rear_uni', 'C2_rear_sph', 'EF_rear_cyl', 'chassis', 'ground', 'uca_rr', 'lca_rr', 'upright_rr', 'tie_rr', 'd1_rr', 'd2_rr', 'wheel_rr', 'uca_lr', 'lca_lr', 'upright_lr', 'tie_lr', 'd1_lr', 'd2_lr', 'wheel_lr', 'uca_rf', 'lca_rf', 'upright_rf', 'tie_rf', 'd1_rf', 'd2_rf', 'wheel_rf', 'uca_lf', 'lca_lf', 'upright_lf', 'tie_lf', 'd1_lf', 'd2_lf', 'wheel_lf', 'l1_rear', 'l2_rear', 'l3_rear', 'l4_rear', 'l5_rear', 'wc_lf_rev_actuator', 'wc_rf_rev_actuator', 'wc_lr_rev_actuator', 'wc_rr_rev_actuator', 'l5_rear.y_actuator'])
def eq(q,bodies,joints,actuators): 
	 eq_s['ucaf_lf_rev']=joints['ucaf_lf_rev'].equations(q)
	 eq_s['lcaf_lf_rev']=joints['lcaf_lf_rev'].equations(q)
	 eq_s['ucao_lf_sph']=joints['ucao_lf_sph'].equations(q)
	 eq_s['lcao_lf_sph']=joints['lcao_lf_sph'].equations(q)
	 eq_s['tro_lf_sph']=joints['tro_lf_sph'].equations(q)
	 eq_s['ch_sh_lf_uni']=joints['ch_sh_lf_uni'].equations(q)
	 eq_s['sh_lca_lf_uni']=joints['sh_lca_lf_uni'].equations(q)
	 eq_s['tri_lf_uni']=joints['tri_lf_uni'].equations(q)
	 eq_s['d_m_lf_cyl']=joints['d_m_lf_cyl'].equations(q)
	 eq_s['wc_lf_rev']=joints['wc_lf_rev'].equations(q)
	 eq_s['ucaf_rr_rev']=joints['ucaf_rr_rev'].equations(q)
	 eq_s['lcaf_rr_rev']=joints['lcaf_rr_rev'].equations(q)
	 eq_s['ucao_rr_sph']=joints['ucao_rr_sph'].equations(q)
	 eq_s['lcao_rr_sph']=joints['lcao_rr_sph'].equations(q)
	 eq_s['tro_rr_sph']=joints['tro_rr_sph'].equations(q)
	 eq_s['ch_sh_rr_uni']=joints['ch_sh_rr_uni'].equations(q)
	 eq_s['sh_lca_rr_uni']=joints['sh_lca_rr_uni'].equations(q)
	 eq_s['tri_rr_uni']=joints['tri_rr_uni'].equations(q)
	 eq_s['d_m_rr_cyl']=joints['d_m_rr_cyl'].equations(q)
	 eq_s['wc_rr_rev']=joints['wc_rr_rev'].equations(q)
	 eq_s['ucaf_rf_rev']=joints['ucaf_rf_rev'].equations(q)
	 eq_s['lcaf_rf_rev']=joints['lcaf_rf_rev'].equations(q)
	 eq_s['ucao_rf_sph']=joints['ucao_rf_sph'].equations(q)
	 eq_s['lcao_rf_sph']=joints['lcao_rf_sph'].equations(q)
	 eq_s['tro_rf_sph']=joints['tro_rf_sph'].equations(q)
	 eq_s['ch_sh_rf_uni']=joints['ch_sh_rf_uni'].equations(q)
	 eq_s['sh_lca_rf_uni']=joints['sh_lca_rf_uni'].equations(q)
	 eq_s['tri_rf_uni']=joints['tri_rf_uni'].equations(q)
	 eq_s['d_m_rf_cyl']=joints['d_m_rf_cyl'].equations(q)
	 eq_s['wc_rf_rev']=joints['wc_rf_rev'].equations(q)
	 eq_s['ucaf_lr_rev']=joints['ucaf_lr_rev'].equations(q)
	 eq_s['lcaf_lr_rev']=joints['lcaf_lr_rev'].equations(q)
	 eq_s['ucao_lr_sph']=joints['ucao_lr_sph'].equations(q)
	 eq_s['lcao_lr_sph']=joints['lcao_lr_sph'].equations(q)
	 eq_s['tro_lr_sph']=joints['tro_lr_sph'].equations(q)
	 eq_s['ch_sh_lr_uni']=joints['ch_sh_lr_uni'].equations(q)
	 eq_s['sh_lca_lr_uni']=joints['sh_lca_lr_uni'].equations(q)
	 eq_s['tri_lr_uni']=joints['tri_lr_uni'].equations(q)
	 eq_s['d_m_lr_cyl']=joints['d_m_lr_cyl'].equations(q)
	 eq_s['wc_lr_rev']=joints['wc_lr_rev'].equations(q)
	 eq_s['mount_1_rear_rev']=joints['mount_1_rear_rev'].equations(q)
	 eq_s['mount_2_rear_rev']=joints['mount_2_rear_rev'].equations(q)
	 eq_s['C1_rear_uni']=joints['C1_rear_uni'].equations(q)
	 eq_s['E_rear_uni']=joints['E_rear_uni'].equations(q)
	 eq_s['F_rear_uni']=joints['F_rear_uni'].equations(q)
	 eq_s['C2_rear_sph']=joints['C2_rear_sph'].equations(q)
	 eq_s['EF_rear_cyl']=joints['EF_rear_cyl'].equations(q)
	 eq_s['chassis']=bodies['chassis'].unity_equation(q)
	 eq_s['ground']=bodies['ground'].mount_equation(q)
	 eq_s['uca_rr']=bodies['uca_rr'].unity_equation(q)
	 eq_s['lca_rr']=bodies['lca_rr'].unity_equation(q)
	 eq_s['upright_rr']=bodies['upright_rr'].unity_equation(q)
	 eq_s['tie_rr']=bodies['tie_rr'].unity_equation(q)
	 eq_s['d1_rr']=bodies['d1_rr'].unity_equation(q)
	 eq_s['d2_rr']=bodies['d2_rr'].unity_equation(q)
	 eq_s['wheel_rr']=bodies['wheel_rr'].unity_equation(q)
	 eq_s['uca_lr']=bodies['uca_lr'].unity_equation(q)
	 eq_s['lca_lr']=bodies['lca_lr'].unity_equation(q)
	 eq_s['upright_lr']=bodies['upright_lr'].unity_equation(q)
	 eq_s['tie_lr']=bodies['tie_lr'].unity_equation(q)
	 eq_s['d1_lr']=bodies['d1_lr'].unity_equation(q)
	 eq_s['d2_lr']=bodies['d2_lr'].unity_equation(q)
	 eq_s['wheel_lr']=bodies['wheel_lr'].unity_equation(q)
	 eq_s['uca_rf']=bodies['uca_rf'].unity_equation(q)
	 eq_s['lca_rf']=bodies['lca_rf'].unity_equation(q)
	 eq_s['upright_rf']=bodies['upright_rf'].unity_equation(q)
	 eq_s['tie_rf']=bodies['tie_rf'].unity_equation(q)
	 eq_s['d1_rf']=bodies['d1_rf'].unity_equation(q)
	 eq_s['d2_rf']=bodies['d2_rf'].unity_equation(q)
	 eq_s['wheel_rf']=bodies['wheel_rf'].unity_equation(q)
	 eq_s['uca_lf']=bodies['uca_lf'].unity_equation(q)
	 eq_s['lca_lf']=bodies['lca_lf'].unity_equation(q)
	 eq_s['upright_lf']=bodies['upright_lf'].unity_equation(q)
	 eq_s['tie_lf']=bodies['tie_lf'].unity_equation(q)
	 eq_s['d1_lf']=bodies['d1_lf'].unity_equation(q)
	 eq_s['d2_lf']=bodies['d2_lf'].unity_equation(q)
	 eq_s['wheel_lf']=bodies['wheel_lf'].unity_equation(q)
	 eq_s['l1_rear']=bodies['l1_rear'].unity_equation(q)
	 eq_s['l2_rear']=bodies['l2_rear'].unity_equation(q)
	 eq_s['l3_rear']=bodies['l3_rear'].unity_equation(q)
	 eq_s['l4_rear']=bodies['l4_rear'].unity_equation(q)
	 eq_s['l5_rear']=bodies['l5_rear'].unity_equation(q)
	 eq_s['wc_lf_rev_actuator']=actuators['wc_lf_rev_actuator'].equations(q)
	 eq_s['wc_rf_rev_actuator']=actuators['wc_rf_rev_actuator'].equations(q)
	 eq_s['wc_lr_rev_actuator']=actuators['wc_lr_rev_actuator'].equations(q)
	 eq_s['wc_rr_rev_actuator']=actuators['wc_rr_rev_actuator'].equations(q)
	 eq_s['l5_rear.y_actuator']=actuators['l5_rear.y_actuator'].equations(q)
	 system=sparse.bmat(eq_s.values.reshape((87,1)),format='csc') 
	 return system.A.reshape((235,)) 


vel_rhs_s=pd.Series([87 *[None]],index=['ucaf_lf_rev', 'lcaf_lf_rev', 'ucao_lf_sph', 'lcao_lf_sph', 'tro_lf_sph', 'ch_sh_lf_uni', 'sh_lca_lf_uni', 'tri_lf_uni', 'd_m_lf_cyl', 'wc_lf_rev', 'ucaf_rr_rev', 'lcaf_rr_rev', 'ucao_rr_sph', 'lcao_rr_sph', 'tro_rr_sph', 'ch_sh_rr_uni', 'sh_lca_rr_uni', 'tri_rr_uni', 'd_m_rr_cyl', 'wc_rr_rev', 'ucaf_rf_rev', 'lcaf_rf_rev', 'ucao_rf_sph', 'lcao_rf_sph', 'tro_rf_sph', 'ch_sh_rf_uni', 'sh_lca_rf_uni', 'tri_rf_uni', 'd_m_rf_cyl', 'wc_rf_rev', 'ucaf_lr_rev', 'lcaf_lr_rev', 'ucao_lr_sph', 'lcao_lr_sph', 'tro_lr_sph', 'ch_sh_lr_uni', 'sh_lca_lr_uni', 'tri_lr_uni', 'd_m_lr_cyl', 'wc_lr_rev', 'mount_1_rear_rev', 'mount_2_rear_rev', 'C1_rear_uni', 'E_rear_uni', 'F_rear_uni', 'C2_rear_sph', 'EF_rear_cyl', 'chassis', 'ground', 'uca_rr', 'lca_rr', 'upright_rr', 'tie_rr', 'd1_rr', 'd2_rr', 'wheel_rr', 'uca_lr', 'lca_lr', 'upright_lr', 'tie_lr', 'd1_lr', 'd2_lr', 'wheel_lr', 'uca_rf', 'lca_rf', 'upright_rf', 'tie_rf', 'd1_rf', 'd2_rf', 'wheel_rf', 'uca_lf', 'lca_lf', 'upright_lf', 'tie_lf', 'd1_lf', 'd2_lf', 'wheel_lf', 'l1_rear', 'l2_rear', 'l3_rear', 'l4_rear', 'l5_rear', 'wc_lf_rev_actuator', 'wc_rf_rev_actuator', 'wc_lr_rev_actuator', 'wc_rr_rev_actuator', 'l5_rear.y_actuator'])
def vel_rhs(actuators): 
	 vrhs=np.zeros((230,1))
	 vrhs=np.concatenate([vrhs,actuators['wc_lf_rev_actuator'].vel_rhs()]) 
	 vrhs=np.concatenate([vrhs,actuators['wc_rf_rev_actuator'].vel_rhs()]) 
	 vrhs=np.concatenate([vrhs,actuators['wc_lr_rev_actuator'].vel_rhs()]) 
	 vrhs=np.concatenate([vrhs,actuators['wc_rr_rev_actuator'].vel_rhs()]) 
	 vrhs=np.concatenate([vrhs,actuators['l5_rear.y_actuator'].vel_rhs()]) 
	 return vrhs 
acc_rhs_s=pd.Series([87 *[None]],index=['ucaf_lf_rev', 'lcaf_lf_rev', 'ucao_lf_sph', 'lcao_lf_sph', 'tro_lf_sph', 'ch_sh_lf_uni', 'sh_lca_lf_uni', 'tri_lf_uni', 'd_m_lf_cyl', 'wc_lf_rev', 'ucaf_rr_rev', 'lcaf_rr_rev', 'ucao_rr_sph', 'lcao_rr_sph', 'tro_rr_sph', 'ch_sh_rr_uni', 'sh_lca_rr_uni', 'tri_rr_uni', 'd_m_rr_cyl', 'wc_rr_rev', 'ucaf_rf_rev', 'lcaf_rf_rev', 'ucao_rf_sph', 'lcao_rf_sph', 'tro_rf_sph', 'ch_sh_rf_uni', 'sh_lca_rf_uni', 'tri_rf_uni', 'd_m_rf_cyl', 'wc_rf_rev', 'ucaf_lr_rev', 'lcaf_lr_rev', 'ucao_lr_sph', 'lcao_lr_sph', 'tro_lr_sph', 'ch_sh_lr_uni', 'sh_lca_lr_uni', 'tri_lr_uni', 'd_m_lr_cyl', 'wc_lr_rev', 'mount_1_rear_rev', 'mount_2_rear_rev', 'C1_rear_uni', 'E_rear_uni', 'F_rear_uni', 'C2_rear_sph', 'EF_rear_cyl', 'chassis', 'ground', 'uca_rr', 'lca_rr', 'upright_rr', 'tie_rr', 'd1_rr', 'd2_rr', 'wheel_rr', 'uca_lr', 'lca_lr', 'upright_lr', 'tie_lr', 'd1_lr', 'd2_lr', 'wheel_lr', 'uca_rf', 'lca_rf', 'upright_rf', 'tie_rf', 'd1_rf', 'd2_rf', 'wheel_rf', 'uca_lf', 'lca_lf', 'upright_lf', 'tie_lf', 'd1_lf', 'd2_lf', 'wheel_lf', 'l1_rear', 'l2_rear', 'l3_rear', 'l4_rear', 'l5_rear', 'wc_lf_rev_actuator', 'wc_rf_rev_actuator', 'wc_lr_rev_actuator', 'wc_rr_rev_actuator', 'l5_rear.y_actuator'])
def acc_rhs(q,qdot,bodies,joints,actuators): 
	 acc_rhs_s['ucaf_lf_rev']=joints['ucaf_lf_rev'].acc_rhs(q,qdot)
	 acc_rhs_s['lcaf_lf_rev']=joints['lcaf_lf_rev'].acc_rhs(q,qdot)
	 acc_rhs_s['ucao_lf_sph']=joints['ucao_lf_sph'].acc_rhs(q,qdot)
	 acc_rhs_s['lcao_lf_sph']=joints['lcao_lf_sph'].acc_rhs(q,qdot)
	 acc_rhs_s['tro_lf_sph']=joints['tro_lf_sph'].acc_rhs(q,qdot)
	 acc_rhs_s['ch_sh_lf_uni']=joints['ch_sh_lf_uni'].acc_rhs(q,qdot)
	 acc_rhs_s['sh_lca_lf_uni']=joints['sh_lca_lf_uni'].acc_rhs(q,qdot)
	 acc_rhs_s['tri_lf_uni']=joints['tri_lf_uni'].acc_rhs(q,qdot)
	 acc_rhs_s['d_m_lf_cyl']=joints['d_m_lf_cyl'].acc_rhs(q,qdot)
	 acc_rhs_s['wc_lf_rev']=joints['wc_lf_rev'].acc_rhs(q,qdot)
	 acc_rhs_s['ucaf_rr_rev']=joints['ucaf_rr_rev'].acc_rhs(q,qdot)
	 acc_rhs_s['lcaf_rr_rev']=joints['lcaf_rr_rev'].acc_rhs(q,qdot)
	 acc_rhs_s['ucao_rr_sph']=joints['ucao_rr_sph'].acc_rhs(q,qdot)
	 acc_rhs_s['lcao_rr_sph']=joints['lcao_rr_sph'].acc_rhs(q,qdot)
	 acc_rhs_s['tro_rr_sph']=joints['tro_rr_sph'].acc_rhs(q,qdot)
	 acc_rhs_s['ch_sh_rr_uni']=joints['ch_sh_rr_uni'].acc_rhs(q,qdot)
	 acc_rhs_s['sh_lca_rr_uni']=joints['sh_lca_rr_uni'].acc_rhs(q,qdot)
	 acc_rhs_s['tri_rr_uni']=joints['tri_rr_uni'].acc_rhs(q,qdot)
	 acc_rhs_s['d_m_rr_cyl']=joints['d_m_rr_cyl'].acc_rhs(q,qdot)
	 acc_rhs_s['wc_rr_rev']=joints['wc_rr_rev'].acc_rhs(q,qdot)
	 acc_rhs_s['ucaf_rf_rev']=joints['ucaf_rf_rev'].acc_rhs(q,qdot)
	 acc_rhs_s['lcaf_rf_rev']=joints['lcaf_rf_rev'].acc_rhs(q,qdot)
	 acc_rhs_s['ucao_rf_sph']=joints['ucao_rf_sph'].acc_rhs(q,qdot)
	 acc_rhs_s['lcao_rf_sph']=joints['lcao_rf_sph'].acc_rhs(q,qdot)
	 acc_rhs_s['tro_rf_sph']=joints['tro_rf_sph'].acc_rhs(q,qdot)
	 acc_rhs_s['ch_sh_rf_uni']=joints['ch_sh_rf_uni'].acc_rhs(q,qdot)
	 acc_rhs_s['sh_lca_rf_uni']=joints['sh_lca_rf_uni'].acc_rhs(q,qdot)
	 acc_rhs_s['tri_rf_uni']=joints['tri_rf_uni'].acc_rhs(q,qdot)
	 acc_rhs_s['d_m_rf_cyl']=joints['d_m_rf_cyl'].acc_rhs(q,qdot)
	 acc_rhs_s['wc_rf_rev']=joints['wc_rf_rev'].acc_rhs(q,qdot)
	 acc_rhs_s['ucaf_lr_rev']=joints['ucaf_lr_rev'].acc_rhs(q,qdot)
	 acc_rhs_s['lcaf_lr_rev']=joints['lcaf_lr_rev'].acc_rhs(q,qdot)
	 acc_rhs_s['ucao_lr_sph']=joints['ucao_lr_sph'].acc_rhs(q,qdot)
	 acc_rhs_s['lcao_lr_sph']=joints['lcao_lr_sph'].acc_rhs(q,qdot)
	 acc_rhs_s['tro_lr_sph']=joints['tro_lr_sph'].acc_rhs(q,qdot)
	 acc_rhs_s['ch_sh_lr_uni']=joints['ch_sh_lr_uni'].acc_rhs(q,qdot)
	 acc_rhs_s['sh_lca_lr_uni']=joints['sh_lca_lr_uni'].acc_rhs(q,qdot)
	 acc_rhs_s['tri_lr_uni']=joints['tri_lr_uni'].acc_rhs(q,qdot)
	 acc_rhs_s['d_m_lr_cyl']=joints['d_m_lr_cyl'].acc_rhs(q,qdot)
	 acc_rhs_s['wc_lr_rev']=joints['wc_lr_rev'].acc_rhs(q,qdot)
	 acc_rhs_s['mount_1_rear_rev']=joints['mount_1_rear_rev'].acc_rhs(q,qdot)
	 acc_rhs_s['mount_2_rear_rev']=joints['mount_2_rear_rev'].acc_rhs(q,qdot)
	 acc_rhs_s['C1_rear_uni']=joints['C1_rear_uni'].acc_rhs(q,qdot)
	 acc_rhs_s['E_rear_uni']=joints['E_rear_uni'].acc_rhs(q,qdot)
	 acc_rhs_s['F_rear_uni']=joints['F_rear_uni'].acc_rhs(q,qdot)
	 acc_rhs_s['C2_rear_sph']=joints['C2_rear_sph'].acc_rhs(q,qdot)
	 acc_rhs_s['EF_rear_cyl']=joints['EF_rear_cyl'].acc_rhs(q,qdot)
	 acc_rhs_s['chassis']=bodies['chassis'].acc_rhs(qdot)
	 acc_rhs_s['ground']=bodies['ground'].mount_acc_rhs(qdot)
	 acc_rhs_s['uca_rr']=bodies['uca_rr'].acc_rhs(qdot)
	 acc_rhs_s['lca_rr']=bodies['lca_rr'].acc_rhs(qdot)
	 acc_rhs_s['upright_rr']=bodies['upright_rr'].acc_rhs(qdot)
	 acc_rhs_s['tie_rr']=bodies['tie_rr'].acc_rhs(qdot)
	 acc_rhs_s['d1_rr']=bodies['d1_rr'].acc_rhs(qdot)
	 acc_rhs_s['d2_rr']=bodies['d2_rr'].acc_rhs(qdot)
	 acc_rhs_s['wheel_rr']=bodies['wheel_rr'].acc_rhs(qdot)
	 acc_rhs_s['uca_lr']=bodies['uca_lr'].acc_rhs(qdot)
	 acc_rhs_s['lca_lr']=bodies['lca_lr'].acc_rhs(qdot)
	 acc_rhs_s['upright_lr']=bodies['upright_lr'].acc_rhs(qdot)
	 acc_rhs_s['tie_lr']=bodies['tie_lr'].acc_rhs(qdot)
	 acc_rhs_s['d1_lr']=bodies['d1_lr'].acc_rhs(qdot)
	 acc_rhs_s['d2_lr']=bodies['d2_lr'].acc_rhs(qdot)
	 acc_rhs_s['wheel_lr']=bodies['wheel_lr'].acc_rhs(qdot)
	 acc_rhs_s['uca_rf']=bodies['uca_rf'].acc_rhs(qdot)
	 acc_rhs_s['lca_rf']=bodies['lca_rf'].acc_rhs(qdot)
	 acc_rhs_s['upright_rf']=bodies['upright_rf'].acc_rhs(qdot)
	 acc_rhs_s['tie_rf']=bodies['tie_rf'].acc_rhs(qdot)
	 acc_rhs_s['d1_rf']=bodies['d1_rf'].acc_rhs(qdot)
	 acc_rhs_s['d2_rf']=bodies['d2_rf'].acc_rhs(qdot)
	 acc_rhs_s['wheel_rf']=bodies['wheel_rf'].acc_rhs(qdot)
	 acc_rhs_s['uca_lf']=bodies['uca_lf'].acc_rhs(qdot)
	 acc_rhs_s['lca_lf']=bodies['lca_lf'].acc_rhs(qdot)
	 acc_rhs_s['upright_lf']=bodies['upright_lf'].acc_rhs(qdot)
	 acc_rhs_s['tie_lf']=bodies['tie_lf'].acc_rhs(qdot)
	 acc_rhs_s['d1_lf']=bodies['d1_lf'].acc_rhs(qdot)
	 acc_rhs_s['d2_lf']=bodies['d2_lf'].acc_rhs(qdot)
	 acc_rhs_s['wheel_lf']=bodies['wheel_lf'].acc_rhs(qdot)
	 acc_rhs_s['l1_rear']=bodies['l1_rear'].acc_rhs(qdot)
	 acc_rhs_s['l2_rear']=bodies['l2_rear'].acc_rhs(qdot)
	 acc_rhs_s['l3_rear']=bodies['l3_rear'].acc_rhs(qdot)
	 acc_rhs_s['l4_rear']=bodies['l4_rear'].acc_rhs(qdot)
	 acc_rhs_s['l5_rear']=bodies['l5_rear'].acc_rhs(qdot)
	 acc_rhs_s['wc_lf_rev_actuator']=actuators['wc_lf_rev_actuator'].acc_rhs(q,qdot)
	 acc_rhs_s['wc_rf_rev_actuator']=actuators['wc_rf_rev_actuator'].acc_rhs(q,qdot)
	 acc_rhs_s['wc_lr_rev_actuator']=actuators['wc_lr_rev_actuator'].acc_rhs(q,qdot)
	 acc_rhs_s['wc_rr_rev_actuator']=actuators['wc_rr_rev_actuator'].acc_rhs(q,qdot)
	 acc_rhs_s['l5_rear.y_actuator']=actuators['l5_rear.y_actuator'].acc_rhs(q,qdot)
	 system=sparse.bmat(acc_rhs_s.values.reshape((87,1)),format='csc') 
	 return system.A.reshape((235,)) 


mass_matrix_df=pd.DataFrame([35 *[None]],columns=['chassis', 'ground', 'uca_rr', 'lca_rr', 'upright_rr', 'tie_rr', 'd1_rr', 'd2_rr', 'wheel_rr', 'uca_lr', 'lca_lr', 'upright_lr', 'tie_lr', 'd1_lr', 'd2_lr', 'wheel_lr', 'uca_rf', 'lca_rf', 'upright_rf', 'tie_rf', 'd1_rf', 'd2_rf', 'wheel_rf', 'uca_lf', 'lca_lf', 'upright_lf', 'tie_lf', 'd1_lf', 'd2_lf', 'wheel_lf', 'l1_rear', 'l2_rear', 'l3_rear', 'l4_rear', 'l5_rear'],index=['chassis', 'ground', 'uca_rr', 'lca_rr', 'upright_rr', 'tie_rr', 'd1_rr', 'd2_rr', 'wheel_rr', 'uca_lr', 'lca_lr', 'upright_lr', 'tie_lr', 'd1_lr', 'd2_lr', 'wheel_lr', 'uca_rf', 'lca_rf', 'upright_rf', 'tie_rf', 'd1_rf', 'd2_rf', 'wheel_rf', 'uca_lf', 'lca_lf', 'upright_lf', 'tie_lf', 'd1_lf', 'd2_lf', 'wheel_lf', 'l1_rear', 'l2_rear', 'l3_rear', 'l4_rear', 'l5_rear'])
def mass_matrix(q,bodies): 
	 mass_matrix_df.loc['chassis','chassis']=bodies['chassis'].mass_matrix(q)
	 mass_matrix_df.loc['ground','ground']=bodies['ground'].mass_matrix(q)
	 mass_matrix_df.loc['uca_rr','uca_rr']=bodies['uca_rr'].mass_matrix(q)
	 mass_matrix_df.loc['lca_rr','lca_rr']=bodies['lca_rr'].mass_matrix(q)
	 mass_matrix_df.loc['upright_rr','upright_rr']=bodies['upright_rr'].mass_matrix(q)
	 mass_matrix_df.loc['tie_rr','tie_rr']=bodies['tie_rr'].mass_matrix(q)
	 mass_matrix_df.loc['d1_rr','d1_rr']=bodies['d1_rr'].mass_matrix(q)
	 mass_matrix_df.loc['d2_rr','d2_rr']=bodies['d2_rr'].mass_matrix(q)
	 mass_matrix_df.loc['wheel_rr','wheel_rr']=bodies['wheel_rr'].mass_matrix(q)
	 mass_matrix_df.loc['uca_lr','uca_lr']=bodies['uca_lr'].mass_matrix(q)
	 mass_matrix_df.loc['lca_lr','lca_lr']=bodies['lca_lr'].mass_matrix(q)
	 mass_matrix_df.loc['upright_lr','upright_lr']=bodies['upright_lr'].mass_matrix(q)
	 mass_matrix_df.loc['tie_lr','tie_lr']=bodies['tie_lr'].mass_matrix(q)
	 mass_matrix_df.loc['d1_lr','d1_lr']=bodies['d1_lr'].mass_matrix(q)
	 mass_matrix_df.loc['d2_lr','d2_lr']=bodies['d2_lr'].mass_matrix(q)
	 mass_matrix_df.loc['wheel_lr','wheel_lr']=bodies['wheel_lr'].mass_matrix(q)
	 mass_matrix_df.loc['uca_rf','uca_rf']=bodies['uca_rf'].mass_matrix(q)
	 mass_matrix_df.loc['lca_rf','lca_rf']=bodies['lca_rf'].mass_matrix(q)
	 mass_matrix_df.loc['upright_rf','upright_rf']=bodies['upright_rf'].mass_matrix(q)
	 mass_matrix_df.loc['tie_rf','tie_rf']=bodies['tie_rf'].mass_matrix(q)
	 mass_matrix_df.loc['d1_rf','d1_rf']=bodies['d1_rf'].mass_matrix(q)
	 mass_matrix_df.loc['d2_rf','d2_rf']=bodies['d2_rf'].mass_matrix(q)
	 mass_matrix_df.loc['wheel_rf','wheel_rf']=bodies['wheel_rf'].mass_matrix(q)
	 mass_matrix_df.loc['uca_lf','uca_lf']=bodies['uca_lf'].mass_matrix(q)
	 mass_matrix_df.loc['lca_lf','lca_lf']=bodies['lca_lf'].mass_matrix(q)
	 mass_matrix_df.loc['upright_lf','upright_lf']=bodies['upright_lf'].mass_matrix(q)
	 mass_matrix_df.loc['tie_lf','tie_lf']=bodies['tie_lf'].mass_matrix(q)
	 mass_matrix_df.loc['d1_lf','d1_lf']=bodies['d1_lf'].mass_matrix(q)
	 mass_matrix_df.loc['d2_lf','d2_lf']=bodies['d2_lf'].mass_matrix(q)
	 mass_matrix_df.loc['wheel_lf','wheel_lf']=bodies['wheel_lf'].mass_matrix(q)
	 mass_matrix_df.loc['l1_rear','l1_rear']=bodies['l1_rear'].mass_matrix(q)
	 mass_matrix_df.loc['l2_rear','l2_rear']=bodies['l2_rear'].mass_matrix(q)
	 mass_matrix_df.loc['l3_rear','l3_rear']=bodies['l3_rear'].mass_matrix(q)
	 mass_matrix_df.loc['l4_rear','l4_rear']=bodies['l4_rear'].mass_matrix(q)
	 mass_matrix_df.loc['l5_rear','l5_rear']=bodies['l5_rear'].mass_matrix(q)
	 mass_matrix=sparse.bmat(mass_matrix_df,format='csc') 
	 return mass_matrix 


Qg_s=pd.Series([35 *np.zeros((7,1))],index=['chassis', 'ground', 'uca_rr', 'lca_rr', 'upright_rr', 'tie_rr', 'd1_rr', 'd2_rr', 'wheel_rr', 'uca_lr', 'lca_lr', 'upright_lr', 'tie_lr', 'd1_lr', 'd2_lr', 'wheel_lr', 'uca_rf', 'lca_rf', 'upright_rf', 'tie_rf', 'd1_rf', 'd2_rf', 'wheel_rf', 'uca_lf', 'lca_lf', 'upright_lf', 'tie_lf', 'd1_lf', 'd2_lf', 'wheel_lf', 'l1_rear', 'l2_rear', 'l3_rear', 'l4_rear', 'l5_rear'])
def Qg(bodies): 
	 Qg_s['chassis']=bodies['chassis'].gravity()
	 Qg_s['ground']=bodies['ground'].gravity()
	 Qg_s['uca_rr']=bodies['uca_rr'].gravity()
	 Qg_s['lca_rr']=bodies['lca_rr'].gravity()
	 Qg_s['upright_rr']=bodies['upright_rr'].gravity()
	 Qg_s['tie_rr']=bodies['tie_rr'].gravity()
	 Qg_s['d1_rr']=bodies['d1_rr'].gravity()
	 Qg_s['d2_rr']=bodies['d2_rr'].gravity()
	 Qg_s['wheel_rr']=bodies['wheel_rr'].gravity()
	 Qg_s['uca_lr']=bodies['uca_lr'].gravity()
	 Qg_s['lca_lr']=bodies['lca_lr'].gravity()
	 Qg_s['upright_lr']=bodies['upright_lr'].gravity()
	 Qg_s['tie_lr']=bodies['tie_lr'].gravity()
	 Qg_s['d1_lr']=bodies['d1_lr'].gravity()
	 Qg_s['d2_lr']=bodies['d2_lr'].gravity()
	 Qg_s['wheel_lr']=bodies['wheel_lr'].gravity()
	 Qg_s['uca_rf']=bodies['uca_rf'].gravity()
	 Qg_s['lca_rf']=bodies['lca_rf'].gravity()
	 Qg_s['upright_rf']=bodies['upright_rf'].gravity()
	 Qg_s['tie_rf']=bodies['tie_rf'].gravity()
	 Qg_s['d1_rf']=bodies['d1_rf'].gravity()
	 Qg_s['d2_rf']=bodies['d2_rf'].gravity()
	 Qg_s['wheel_rf']=bodies['wheel_rf'].gravity()
	 Qg_s['uca_lf']=bodies['uca_lf'].gravity()
	 Qg_s['lca_lf']=bodies['lca_lf'].gravity()
	 Qg_s['upright_lf']=bodies['upright_lf'].gravity()
	 Qg_s['tie_lf']=bodies['tie_lf'].gravity()
	 Qg_s['d1_lf']=bodies['d1_lf'].gravity()
	 Qg_s['d2_lf']=bodies['d2_lf'].gravity()
	 Qg_s['wheel_lf']=bodies['wheel_lf'].gravity()
	 Qg_s['l1_rear']=bodies['l1_rear'].gravity()
	 Qg_s['l2_rear']=bodies['l2_rear'].gravity()
	 Qg_s['l3_rear']=bodies['l3_rear'].gravity()
	 Qg_s['l4_rear']=bodies['l4_rear'].gravity()
	 Qg_s['l5_rear']=bodies['l5_rear'].gravity()
	 system=sparse.bmat(Qg_s.values.reshape((35,1)),format='csc') 
	 return system.A.reshape((245,)) 


Qv_s=pd.Series([35 *np.zeros((7,1))],index=['chassis', 'ground', 'uca_rr', 'lca_rr', 'upright_rr', 'tie_rr', 'd1_rr', 'd2_rr', 'wheel_rr', 'uca_lr', 'lca_lr', 'upright_lr', 'tie_lr', 'd1_lr', 'd2_lr', 'wheel_lr', 'uca_rf', 'lca_rf', 'upright_rf', 'tie_rf', 'd1_rf', 'd2_rf', 'wheel_rf', 'uca_lf', 'lca_lf', 'upright_lf', 'tie_lf', 'd1_lf', 'd2_lf', 'wheel_lf', 'l1_rear', 'l2_rear', 'l3_rear', 'l4_rear', 'l5_rear'])
def Qv(bodies,q,qdot): 
	 Qv_s['chassis']=bodies['chassis'].centrifugal(q,qdot)
	 Qv_s['ground']=bodies['ground'].centrifugal(q,qdot)
	 Qv_s['uca_rr']=bodies['uca_rr'].centrifugal(q,qdot)
	 Qv_s['lca_rr']=bodies['lca_rr'].centrifugal(q,qdot)
	 Qv_s['upright_rr']=bodies['upright_rr'].centrifugal(q,qdot)
	 Qv_s['tie_rr']=bodies['tie_rr'].centrifugal(q,qdot)
	 Qv_s['d1_rr']=bodies['d1_rr'].centrifugal(q,qdot)
	 Qv_s['d2_rr']=bodies['d2_rr'].centrifugal(q,qdot)
	 Qv_s['wheel_rr']=bodies['wheel_rr'].centrifugal(q,qdot)
	 Qv_s['uca_lr']=bodies['uca_lr'].centrifugal(q,qdot)
	 Qv_s['lca_lr']=bodies['lca_lr'].centrifugal(q,qdot)
	 Qv_s['upright_lr']=bodies['upright_lr'].centrifugal(q,qdot)
	 Qv_s['tie_lr']=bodies['tie_lr'].centrifugal(q,qdot)
	 Qv_s['d1_lr']=bodies['d1_lr'].centrifugal(q,qdot)
	 Qv_s['d2_lr']=bodies['d2_lr'].centrifugal(q,qdot)
	 Qv_s['wheel_lr']=bodies['wheel_lr'].centrifugal(q,qdot)
	 Qv_s['uca_rf']=bodies['uca_rf'].centrifugal(q,qdot)
	 Qv_s['lca_rf']=bodies['lca_rf'].centrifugal(q,qdot)
	 Qv_s['upright_rf']=bodies['upright_rf'].centrifugal(q,qdot)
	 Qv_s['tie_rf']=bodies['tie_rf'].centrifugal(q,qdot)
	 Qv_s['d1_rf']=bodies['d1_rf'].centrifugal(q,qdot)
	 Qv_s['d2_rf']=bodies['d2_rf'].centrifugal(q,qdot)
	 Qv_s['wheel_rf']=bodies['wheel_rf'].centrifugal(q,qdot)
	 Qv_s['uca_lf']=bodies['uca_lf'].centrifugal(q,qdot)
	 Qv_s['lca_lf']=bodies['lca_lf'].centrifugal(q,qdot)
	 Qv_s['upright_lf']=bodies['upright_lf'].centrifugal(q,qdot)
	 Qv_s['tie_lf']=bodies['tie_lf'].centrifugal(q,qdot)
	 Qv_s['d1_lf']=bodies['d1_lf'].centrifugal(q,qdot)
	 Qv_s['d2_lf']=bodies['d2_lf'].centrifugal(q,qdot)
	 Qv_s['wheel_lf']=bodies['wheel_lf'].centrifugal(q,qdot)
	 Qv_s['l1_rear']=bodies['l1_rear'].centrifugal(q,qdot)
	 Qv_s['l2_rear']=bodies['l2_rear'].centrifugal(q,qdot)
	 Qv_s['l3_rear']=bodies['l3_rear'].centrifugal(q,qdot)
	 Qv_s['l4_rear']=bodies['l4_rear'].centrifugal(q,qdot)
	 Qv_s['l5_rear']=bodies['l5_rear'].centrifugal(q,qdot)
	 system=sparse.bmat(Qv_s.values.reshape((35,1)),format='csc') 
	 return system.A.reshape((245,)) 


Qa_s=pd.Series([35 *np.zeros((7,1))],index=['chassis', 'ground', 'uca_rr', 'lca_rr', 'upright_rr', 'tie_rr', 'd1_rr', 'd2_rr', 'wheel_rr', 'uca_lr', 'lca_lr', 'upright_lr', 'tie_lr', 'd1_lr', 'd2_lr', 'wheel_lr', 'uca_rf', 'lca_rf', 'upright_rf', 'tie_rf', 'd1_rf', 'd2_rf', 'wheel_rf', 'uca_lf', 'lca_lf', 'upright_lf', 'tie_lf', 'd1_lf', 'd2_lf', 'wheel_lf', 'l1_rear', 'l2_rear', 'l3_rear', 'l4_rear', 'l5_rear'])
def Qa(forces,q,qdot): 
	 Qi,Qj=forces['gk_w11_rr'].equation(q,qdot) 
	 Qa_s['d1_rr']=Qi
	 Qa_s['d2_rr']=Qj
	 Qi,Qj=forces['gk_w11_lr'].equation(q,qdot) 
	 Qa_s['d1_lr']=Qi
	 Qa_s['d2_lr']=Qj
	 Qi,Qj=forces['gk_w11_rf'].equation(q,qdot) 
	 Qa_s['d1_rf']=Qi
	 Qa_s['d2_rf']=Qj
	 Qi,Qj=forces['gk_w11_lf'].equation(q,qdot) 
	 Qa_s['d1_lf']=Qi
	 Qa_s['d2_lf']=Qj
	 Qa_s['wheel_rr']=forces['tvf_rr'].equation(q,qdot)
	 Qa_s['wheel_lr']=forces['tvf_lr'].equation(q,qdot)
	 Qa_s['wheel_rf']=forces['tvf_rf'].equation(q,qdot)
	 Qa_s['wheel_lf']=forces['tvf_lf'].equation(q,qdot)
	 system=sparse.bmat(Qa_s.values.reshape((35,1)),format='csc') 
	 return system.A.reshape((245,)) 


JR_s=pd.Series(np.zeros((282)),index=['ucaf_lf_rev_Fx', 'ucaf_lf_rev_Fy', 'ucaf_lf_rev_Fz', 'ucaf_lf_rev_Mx', 'ucaf_lf_rev_My', 'ucaf_lf_rev_Mz', 'lcaf_lf_rev_Fx', 'lcaf_lf_rev_Fy', 'lcaf_lf_rev_Fz', 'lcaf_lf_rev_Mx', 'lcaf_lf_rev_My', 'lcaf_lf_rev_Mz', 'ucao_lf_sph_Fx', 'ucao_lf_sph_Fy', 'ucao_lf_sph_Fz', 'ucao_lf_sph_Mx', 'ucao_lf_sph_My', 'ucao_lf_sph_Mz', 'lcao_lf_sph_Fx', 'lcao_lf_sph_Fy', 'lcao_lf_sph_Fz', 'lcao_lf_sph_Mx', 'lcao_lf_sph_My', 'lcao_lf_sph_Mz', 'tro_lf_sph_Fx', 'tro_lf_sph_Fy', 'tro_lf_sph_Fz', 'tro_lf_sph_Mx', 'tro_lf_sph_My', 'tro_lf_sph_Mz', 'ch_sh_lf_uni_Fx', 'ch_sh_lf_uni_Fy', 'ch_sh_lf_uni_Fz', 'ch_sh_lf_uni_Mx', 'ch_sh_lf_uni_My', 'ch_sh_lf_uni_Mz', 'sh_lca_lf_uni_Fx', 'sh_lca_lf_uni_Fy', 'sh_lca_lf_uni_Fz', 'sh_lca_lf_uni_Mx', 'sh_lca_lf_uni_My', 'sh_lca_lf_uni_Mz', 'tri_lf_uni_Fx', 'tri_lf_uni_Fy', 'tri_lf_uni_Fz', 'tri_lf_uni_Mx', 'tri_lf_uni_My', 'tri_lf_uni_Mz', 'd_m_lf_cyl_Fx', 'd_m_lf_cyl_Fy', 'd_m_lf_cyl_Fz', 'd_m_lf_cyl_Mx', 'd_m_lf_cyl_My', 'd_m_lf_cyl_Mz', 'wc_lf_rev_Fx', 'wc_lf_rev_Fy', 'wc_lf_rev_Fz', 'wc_lf_rev_Mx', 'wc_lf_rev_My', 'wc_lf_rev_Mz', 'ucaf_rr_rev_Fx', 'ucaf_rr_rev_Fy', 'ucaf_rr_rev_Fz', 'ucaf_rr_rev_Mx', 'ucaf_rr_rev_My', 'ucaf_rr_rev_Mz', 'lcaf_rr_rev_Fx', 'lcaf_rr_rev_Fy', 'lcaf_rr_rev_Fz', 'lcaf_rr_rev_Mx', 'lcaf_rr_rev_My', 'lcaf_rr_rev_Mz', 'ucao_rr_sph_Fx', 'ucao_rr_sph_Fy', 'ucao_rr_sph_Fz', 'ucao_rr_sph_Mx', 'ucao_rr_sph_My', 'ucao_rr_sph_Mz', 'lcao_rr_sph_Fx', 'lcao_rr_sph_Fy', 'lcao_rr_sph_Fz', 'lcao_rr_sph_Mx', 'lcao_rr_sph_My', 'lcao_rr_sph_Mz', 'tro_rr_sph_Fx', 'tro_rr_sph_Fy', 'tro_rr_sph_Fz', 'tro_rr_sph_Mx', 'tro_rr_sph_My', 'tro_rr_sph_Mz', 'ch_sh_rr_uni_Fx', 'ch_sh_rr_uni_Fy', 'ch_sh_rr_uni_Fz', 'ch_sh_rr_uni_Mx', 'ch_sh_rr_uni_My', 'ch_sh_rr_uni_Mz', 'sh_lca_rr_uni_Fx', 'sh_lca_rr_uni_Fy', 'sh_lca_rr_uni_Fz', 'sh_lca_rr_uni_Mx', 'sh_lca_rr_uni_My', 'sh_lca_rr_uni_Mz', 'tri_rr_uni_Fx', 'tri_rr_uni_Fy', 'tri_rr_uni_Fz', 'tri_rr_uni_Mx', 'tri_rr_uni_My', 'tri_rr_uni_Mz', 'd_m_rr_cyl_Fx', 'd_m_rr_cyl_Fy', 'd_m_rr_cyl_Fz', 'd_m_rr_cyl_Mx', 'd_m_rr_cyl_My', 'd_m_rr_cyl_Mz', 'wc_rr_rev_Fx', 'wc_rr_rev_Fy', 'wc_rr_rev_Fz', 'wc_rr_rev_Mx', 'wc_rr_rev_My', 'wc_rr_rev_Mz', 'ucaf_rf_rev_Fx', 'ucaf_rf_rev_Fy', 'ucaf_rf_rev_Fz', 'ucaf_rf_rev_Mx', 'ucaf_rf_rev_My', 'ucaf_rf_rev_Mz', 'lcaf_rf_rev_Fx', 'lcaf_rf_rev_Fy', 'lcaf_rf_rev_Fz', 'lcaf_rf_rev_Mx', 'lcaf_rf_rev_My', 'lcaf_rf_rev_Mz', 'ucao_rf_sph_Fx', 'ucao_rf_sph_Fy', 'ucao_rf_sph_Fz', 'ucao_rf_sph_Mx', 'ucao_rf_sph_My', 'ucao_rf_sph_Mz', 'lcao_rf_sph_Fx', 'lcao_rf_sph_Fy', 'lcao_rf_sph_Fz', 'lcao_rf_sph_Mx', 'lcao_rf_sph_My', 'lcao_rf_sph_Mz', 'tro_rf_sph_Fx', 'tro_rf_sph_Fy', 'tro_rf_sph_Fz', 'tro_rf_sph_Mx', 'tro_rf_sph_My', 'tro_rf_sph_Mz', 'ch_sh_rf_uni_Fx', 'ch_sh_rf_uni_Fy', 'ch_sh_rf_uni_Fz', 'ch_sh_rf_uni_Mx', 'ch_sh_rf_uni_My', 'ch_sh_rf_uni_Mz', 'sh_lca_rf_uni_Fx', 'sh_lca_rf_uni_Fy', 'sh_lca_rf_uni_Fz', 'sh_lca_rf_uni_Mx', 'sh_lca_rf_uni_My', 'sh_lca_rf_uni_Mz', 'tri_rf_uni_Fx', 'tri_rf_uni_Fy', 'tri_rf_uni_Fz', 'tri_rf_uni_Mx', 'tri_rf_uni_My', 'tri_rf_uni_Mz', 'd_m_rf_cyl_Fx', 'd_m_rf_cyl_Fy', 'd_m_rf_cyl_Fz', 'd_m_rf_cyl_Mx', 'd_m_rf_cyl_My', 'd_m_rf_cyl_Mz', 'wc_rf_rev_Fx', 'wc_rf_rev_Fy', 'wc_rf_rev_Fz', 'wc_rf_rev_Mx', 'wc_rf_rev_My', 'wc_rf_rev_Mz', 'ucaf_lr_rev_Fx', 'ucaf_lr_rev_Fy', 'ucaf_lr_rev_Fz', 'ucaf_lr_rev_Mx', 'ucaf_lr_rev_My', 'ucaf_lr_rev_Mz', 'lcaf_lr_rev_Fx', 'lcaf_lr_rev_Fy', 'lcaf_lr_rev_Fz', 'lcaf_lr_rev_Mx', 'lcaf_lr_rev_My', 'lcaf_lr_rev_Mz', 'ucao_lr_sph_Fx', 'ucao_lr_sph_Fy', 'ucao_lr_sph_Fz', 'ucao_lr_sph_Mx', 'ucao_lr_sph_My', 'ucao_lr_sph_Mz', 'lcao_lr_sph_Fx', 'lcao_lr_sph_Fy', 'lcao_lr_sph_Fz', 'lcao_lr_sph_Mx', 'lcao_lr_sph_My', 'lcao_lr_sph_Mz', 'tro_lr_sph_Fx', 'tro_lr_sph_Fy', 'tro_lr_sph_Fz', 'tro_lr_sph_Mx', 'tro_lr_sph_My', 'tro_lr_sph_Mz', 'ch_sh_lr_uni_Fx', 'ch_sh_lr_uni_Fy', 'ch_sh_lr_uni_Fz', 'ch_sh_lr_uni_Mx', 'ch_sh_lr_uni_My', 'ch_sh_lr_uni_Mz', 'sh_lca_lr_uni_Fx', 'sh_lca_lr_uni_Fy', 'sh_lca_lr_uni_Fz', 'sh_lca_lr_uni_Mx', 'sh_lca_lr_uni_My', 'sh_lca_lr_uni_Mz', 'tri_lr_uni_Fx', 'tri_lr_uni_Fy', 'tri_lr_uni_Fz', 'tri_lr_uni_Mx', 'tri_lr_uni_My', 'tri_lr_uni_Mz', 'd_m_lr_cyl_Fx', 'd_m_lr_cyl_Fy', 'd_m_lr_cyl_Fz', 'd_m_lr_cyl_Mx', 'd_m_lr_cyl_My', 'd_m_lr_cyl_Mz', 'wc_lr_rev_Fx', 'wc_lr_rev_Fy', 'wc_lr_rev_Fz', 'wc_lr_rev_Mx', 'wc_lr_rev_My', 'wc_lr_rev_Mz', 'mount_1_rear_rev_Fx', 'mount_1_rear_rev_Fy', 'mount_1_rear_rev_Fz', 'mount_1_rear_rev_Mx', 'mount_1_rear_rev_My', 'mount_1_rear_rev_Mz', 'mount_2_rear_rev_Fx', 'mount_2_rear_rev_Fy', 'mount_2_rear_rev_Fz', 'mount_2_rear_rev_Mx', 'mount_2_rear_rev_My', 'mount_2_rear_rev_Mz', 'C1_rear_uni_Fx', 'C1_rear_uni_Fy', 'C1_rear_uni_Fz', 'C1_rear_uni_Mx', 'C1_rear_uni_My', 'C1_rear_uni_Mz', 'E_rear_uni_Fx', 'E_rear_uni_Fy', 'E_rear_uni_Fz', 'E_rear_uni_Mx', 'E_rear_uni_My', 'E_rear_uni_Mz', 'F_rear_uni_Fx', 'F_rear_uni_Fy', 'F_rear_uni_Fz', 'F_rear_uni_Mx', 'F_rear_uni_My', 'F_rear_uni_Mz', 'C2_rear_sph_Fx', 'C2_rear_sph_Fy', 'C2_rear_sph_Fz', 'C2_rear_sph_Mx', 'C2_rear_sph_My', 'C2_rear_sph_Mz', 'EF_rear_cyl_Fx', 'EF_rear_cyl_Fy', 'EF_rear_cyl_Fz', 'EF_rear_cyl_Mx', 'EF_rear_cyl_My', 'EF_rear_cyl_Mz'])
def JR(joints,q,lamda): 
	 JR_s[['ucaf_lf_rev_Fx', 'ucaf_lf_rev_Fy', 'ucaf_lf_rev_Fz', 'ucaf_lf_rev_Mx', 'ucaf_lf_rev_My', 'ucaf_lf_rev_Mz']]=joints['ucaf_lf_rev'].reactions(q,lamda)
	 JR_s[['lcaf_lf_rev_Fx', 'lcaf_lf_rev_Fy', 'lcaf_lf_rev_Fz', 'lcaf_lf_rev_Mx', 'lcaf_lf_rev_My', 'lcaf_lf_rev_Mz']]=joints['lcaf_lf_rev'].reactions(q,lamda)
	 JR_s[['ucao_lf_sph_Fx', 'ucao_lf_sph_Fy', 'ucao_lf_sph_Fz', 'ucao_lf_sph_Mx', 'ucao_lf_sph_My', 'ucao_lf_sph_Mz']]=joints['ucao_lf_sph'].reactions(q,lamda)
	 JR_s[['lcao_lf_sph_Fx', 'lcao_lf_sph_Fy', 'lcao_lf_sph_Fz', 'lcao_lf_sph_Mx', 'lcao_lf_sph_My', 'lcao_lf_sph_Mz']]=joints['lcao_lf_sph'].reactions(q,lamda)
	 JR_s[['tro_lf_sph_Fx', 'tro_lf_sph_Fy', 'tro_lf_sph_Fz', 'tro_lf_sph_Mx', 'tro_lf_sph_My', 'tro_lf_sph_Mz']]=joints['tro_lf_sph'].reactions(q,lamda)
	 JR_s[['ch_sh_lf_uni_Fx', 'ch_sh_lf_uni_Fy', 'ch_sh_lf_uni_Fz', 'ch_sh_lf_uni_Mx', 'ch_sh_lf_uni_My', 'ch_sh_lf_uni_Mz']]=joints['ch_sh_lf_uni'].reactions(q,lamda)
	 JR_s[['sh_lca_lf_uni_Fx', 'sh_lca_lf_uni_Fy', 'sh_lca_lf_uni_Fz', 'sh_lca_lf_uni_Mx', 'sh_lca_lf_uni_My', 'sh_lca_lf_uni_Mz']]=joints['sh_lca_lf_uni'].reactions(q,lamda)
	 JR_s[['tri_lf_uni_Fx', 'tri_lf_uni_Fy', 'tri_lf_uni_Fz', 'tri_lf_uni_Mx', 'tri_lf_uni_My', 'tri_lf_uni_Mz']]=joints['tri_lf_uni'].reactions(q,lamda)
	 JR_s[['d_m_lf_cyl_Fx', 'd_m_lf_cyl_Fy', 'd_m_lf_cyl_Fz', 'd_m_lf_cyl_Mx', 'd_m_lf_cyl_My', 'd_m_lf_cyl_Mz']]=joints['d_m_lf_cyl'].reactions(q,lamda)
	 JR_s[['wc_lf_rev_Fx', 'wc_lf_rev_Fy', 'wc_lf_rev_Fz', 'wc_lf_rev_Mx', 'wc_lf_rev_My', 'wc_lf_rev_Mz']]=joints['wc_lf_rev'].reactions(q,lamda)
	 JR_s[['ucaf_rr_rev_Fx', 'ucaf_rr_rev_Fy', 'ucaf_rr_rev_Fz', 'ucaf_rr_rev_Mx', 'ucaf_rr_rev_My', 'ucaf_rr_rev_Mz']]=joints['ucaf_rr_rev'].reactions(q,lamda)
	 JR_s[['lcaf_rr_rev_Fx', 'lcaf_rr_rev_Fy', 'lcaf_rr_rev_Fz', 'lcaf_rr_rev_Mx', 'lcaf_rr_rev_My', 'lcaf_rr_rev_Mz']]=joints['lcaf_rr_rev'].reactions(q,lamda)
	 JR_s[['ucao_rr_sph_Fx', 'ucao_rr_sph_Fy', 'ucao_rr_sph_Fz', 'ucao_rr_sph_Mx', 'ucao_rr_sph_My', 'ucao_rr_sph_Mz']]=joints['ucao_rr_sph'].reactions(q,lamda)
	 JR_s[['lcao_rr_sph_Fx', 'lcao_rr_sph_Fy', 'lcao_rr_sph_Fz', 'lcao_rr_sph_Mx', 'lcao_rr_sph_My', 'lcao_rr_sph_Mz']]=joints['lcao_rr_sph'].reactions(q,lamda)
	 JR_s[['tro_rr_sph_Fx', 'tro_rr_sph_Fy', 'tro_rr_sph_Fz', 'tro_rr_sph_Mx', 'tro_rr_sph_My', 'tro_rr_sph_Mz']]=joints['tro_rr_sph'].reactions(q,lamda)
	 JR_s[['ch_sh_rr_uni_Fx', 'ch_sh_rr_uni_Fy', 'ch_sh_rr_uni_Fz', 'ch_sh_rr_uni_Mx', 'ch_sh_rr_uni_My', 'ch_sh_rr_uni_Mz']]=joints['ch_sh_rr_uni'].reactions(q,lamda)
	 JR_s[['sh_lca_rr_uni_Fx', 'sh_lca_rr_uni_Fy', 'sh_lca_rr_uni_Fz', 'sh_lca_rr_uni_Mx', 'sh_lca_rr_uni_My', 'sh_lca_rr_uni_Mz']]=joints['sh_lca_rr_uni'].reactions(q,lamda)
	 JR_s[['tri_rr_uni_Fx', 'tri_rr_uni_Fy', 'tri_rr_uni_Fz', 'tri_rr_uni_Mx', 'tri_rr_uni_My', 'tri_rr_uni_Mz']]=joints['tri_rr_uni'].reactions(q,lamda)
	 JR_s[['d_m_rr_cyl_Fx', 'd_m_rr_cyl_Fy', 'd_m_rr_cyl_Fz', 'd_m_rr_cyl_Mx', 'd_m_rr_cyl_My', 'd_m_rr_cyl_Mz']]=joints['d_m_rr_cyl'].reactions(q,lamda)
	 JR_s[['wc_rr_rev_Fx', 'wc_rr_rev_Fy', 'wc_rr_rev_Fz', 'wc_rr_rev_Mx', 'wc_rr_rev_My', 'wc_rr_rev_Mz']]=joints['wc_rr_rev'].reactions(q,lamda)
	 JR_s[['ucaf_rf_rev_Fx', 'ucaf_rf_rev_Fy', 'ucaf_rf_rev_Fz', 'ucaf_rf_rev_Mx', 'ucaf_rf_rev_My', 'ucaf_rf_rev_Mz']]=joints['ucaf_rf_rev'].reactions(q,lamda)
	 JR_s[['lcaf_rf_rev_Fx', 'lcaf_rf_rev_Fy', 'lcaf_rf_rev_Fz', 'lcaf_rf_rev_Mx', 'lcaf_rf_rev_My', 'lcaf_rf_rev_Mz']]=joints['lcaf_rf_rev'].reactions(q,lamda)
	 JR_s[['ucao_rf_sph_Fx', 'ucao_rf_sph_Fy', 'ucao_rf_sph_Fz', 'ucao_rf_sph_Mx', 'ucao_rf_sph_My', 'ucao_rf_sph_Mz']]=joints['ucao_rf_sph'].reactions(q,lamda)
	 JR_s[['lcao_rf_sph_Fx', 'lcao_rf_sph_Fy', 'lcao_rf_sph_Fz', 'lcao_rf_sph_Mx', 'lcao_rf_sph_My', 'lcao_rf_sph_Mz']]=joints['lcao_rf_sph'].reactions(q,lamda)
	 JR_s[['tro_rf_sph_Fx', 'tro_rf_sph_Fy', 'tro_rf_sph_Fz', 'tro_rf_sph_Mx', 'tro_rf_sph_My', 'tro_rf_sph_Mz']]=joints['tro_rf_sph'].reactions(q,lamda)
	 JR_s[['ch_sh_rf_uni_Fx', 'ch_sh_rf_uni_Fy', 'ch_sh_rf_uni_Fz', 'ch_sh_rf_uni_Mx', 'ch_sh_rf_uni_My', 'ch_sh_rf_uni_Mz']]=joints['ch_sh_rf_uni'].reactions(q,lamda)
	 JR_s[['sh_lca_rf_uni_Fx', 'sh_lca_rf_uni_Fy', 'sh_lca_rf_uni_Fz', 'sh_lca_rf_uni_Mx', 'sh_lca_rf_uni_My', 'sh_lca_rf_uni_Mz']]=joints['sh_lca_rf_uni'].reactions(q,lamda)
	 JR_s[['tri_rf_uni_Fx', 'tri_rf_uni_Fy', 'tri_rf_uni_Fz', 'tri_rf_uni_Mx', 'tri_rf_uni_My', 'tri_rf_uni_Mz']]=joints['tri_rf_uni'].reactions(q,lamda)
	 JR_s[['d_m_rf_cyl_Fx', 'd_m_rf_cyl_Fy', 'd_m_rf_cyl_Fz', 'd_m_rf_cyl_Mx', 'd_m_rf_cyl_My', 'd_m_rf_cyl_Mz']]=joints['d_m_rf_cyl'].reactions(q,lamda)
	 JR_s[['wc_rf_rev_Fx', 'wc_rf_rev_Fy', 'wc_rf_rev_Fz', 'wc_rf_rev_Mx', 'wc_rf_rev_My', 'wc_rf_rev_Mz']]=joints['wc_rf_rev'].reactions(q,lamda)
	 JR_s[['ucaf_lr_rev_Fx', 'ucaf_lr_rev_Fy', 'ucaf_lr_rev_Fz', 'ucaf_lr_rev_Mx', 'ucaf_lr_rev_My', 'ucaf_lr_rev_Mz']]=joints['ucaf_lr_rev'].reactions(q,lamda)
	 JR_s[['lcaf_lr_rev_Fx', 'lcaf_lr_rev_Fy', 'lcaf_lr_rev_Fz', 'lcaf_lr_rev_Mx', 'lcaf_lr_rev_My', 'lcaf_lr_rev_Mz']]=joints['lcaf_lr_rev'].reactions(q,lamda)
	 JR_s[['ucao_lr_sph_Fx', 'ucao_lr_sph_Fy', 'ucao_lr_sph_Fz', 'ucao_lr_sph_Mx', 'ucao_lr_sph_My', 'ucao_lr_sph_Mz']]=joints['ucao_lr_sph'].reactions(q,lamda)
	 JR_s[['lcao_lr_sph_Fx', 'lcao_lr_sph_Fy', 'lcao_lr_sph_Fz', 'lcao_lr_sph_Mx', 'lcao_lr_sph_My', 'lcao_lr_sph_Mz']]=joints['lcao_lr_sph'].reactions(q,lamda)
	 JR_s[['tro_lr_sph_Fx', 'tro_lr_sph_Fy', 'tro_lr_sph_Fz', 'tro_lr_sph_Mx', 'tro_lr_sph_My', 'tro_lr_sph_Mz']]=joints['tro_lr_sph'].reactions(q,lamda)
	 JR_s[['ch_sh_lr_uni_Fx', 'ch_sh_lr_uni_Fy', 'ch_sh_lr_uni_Fz', 'ch_sh_lr_uni_Mx', 'ch_sh_lr_uni_My', 'ch_sh_lr_uni_Mz']]=joints['ch_sh_lr_uni'].reactions(q,lamda)
	 JR_s[['sh_lca_lr_uni_Fx', 'sh_lca_lr_uni_Fy', 'sh_lca_lr_uni_Fz', 'sh_lca_lr_uni_Mx', 'sh_lca_lr_uni_My', 'sh_lca_lr_uni_Mz']]=joints['sh_lca_lr_uni'].reactions(q,lamda)
	 JR_s[['tri_lr_uni_Fx', 'tri_lr_uni_Fy', 'tri_lr_uni_Fz', 'tri_lr_uni_Mx', 'tri_lr_uni_My', 'tri_lr_uni_Mz']]=joints['tri_lr_uni'].reactions(q,lamda)
	 JR_s[['d_m_lr_cyl_Fx', 'd_m_lr_cyl_Fy', 'd_m_lr_cyl_Fz', 'd_m_lr_cyl_Mx', 'd_m_lr_cyl_My', 'd_m_lr_cyl_Mz']]=joints['d_m_lr_cyl'].reactions(q,lamda)
	 JR_s[['wc_lr_rev_Fx', 'wc_lr_rev_Fy', 'wc_lr_rev_Fz', 'wc_lr_rev_Mx', 'wc_lr_rev_My', 'wc_lr_rev_Mz']]=joints['wc_lr_rev'].reactions(q,lamda)
	 JR_s[['mount_1_rear_rev_Fx', 'mount_1_rear_rev_Fy', 'mount_1_rear_rev_Fz', 'mount_1_rear_rev_Mx', 'mount_1_rear_rev_My', 'mount_1_rear_rev_Mz']]=joints['mount_1_rear_rev'].reactions(q,lamda)
	 JR_s[['mount_2_rear_rev_Fx', 'mount_2_rear_rev_Fy', 'mount_2_rear_rev_Fz', 'mount_2_rear_rev_Mx', 'mount_2_rear_rev_My', 'mount_2_rear_rev_Mz']]=joints['mount_2_rear_rev'].reactions(q,lamda)
	 JR_s[['C1_rear_uni_Fx', 'C1_rear_uni_Fy', 'C1_rear_uni_Fz', 'C1_rear_uni_Mx', 'C1_rear_uni_My', 'C1_rear_uni_Mz']]=joints['C1_rear_uni'].reactions(q,lamda)
	 JR_s[['E_rear_uni_Fx', 'E_rear_uni_Fy', 'E_rear_uni_Fz', 'E_rear_uni_Mx', 'E_rear_uni_My', 'E_rear_uni_Mz']]=joints['E_rear_uni'].reactions(q,lamda)
	 JR_s[['F_rear_uni_Fx', 'F_rear_uni_Fy', 'F_rear_uni_Fz', 'F_rear_uni_Mx', 'F_rear_uni_My', 'F_rear_uni_Mz']]=joints['F_rear_uni'].reactions(q,lamda)
	 JR_s[['C2_rear_sph_Fx', 'C2_rear_sph_Fy', 'C2_rear_sph_Fz', 'C2_rear_sph_Mx', 'C2_rear_sph_My', 'C2_rear_sph_Mz']]=joints['C2_rear_sph'].reactions(q,lamda)
	 JR_s[['EF_rear_cyl_Fx', 'EF_rear_cyl_Fy', 'EF_rear_cyl_Fz', 'EF_rear_cyl_Mx', 'EF_rear_cyl_My', 'EF_rear_cyl_Mz']]=joints['EF_rear_cyl'].reactions(q,lamda)
	 return JR_s 


